import { Injectable } from "@angular/core";
import { FullSpinnerService } from "src/app/common/full-spinner/full-spinner.service";

@Injectable({
  providedIn: "root",
})
export class MemberRegistration {
  constructor(public fullspinner: FullSpinnerService) {}

  newMember = {
    memberRegistrationId: 0,
    employerRefNo: "",
    orgId: 0,
    firstName: "",
    middleName: "",
    lastName: "",
    brn: "",
    tin: "",
    passportNo: "",
    dateOfBirth: "",
    placeOfBirth: "",
    nationalityId: 0,
    nationalityValue: "",
    genderId: 0,
    genderValue: "",
    fatherName: "",
    motherName: "",
    ethnicityId: 0,
    ethnicityValue: "",
    citizenshipId: 0,
    citizenshipValue: "",
    maritalStatusId: 0,
    maritalStatusValue: "",
    mobileNo: "",
    emailId: "",
    personId: 0,
    peopleHubPersonId: 0,
    optOutOfNominee: "",
    dateStartedWork: "",
    acceptDeclaration: "",
    statusId: 0,
    statusValue: "",
    transactionPin: "",
    declaration: "",
    nationalityDescription: "",
    genderDescription: "",
    ethnicityDescription: "",
    citizenshipDescription: "",
    maritalStatusDescription: "",
    statusDescription: "",
    createdDate: "",
    infoMsg: "",
    memberFullname: "",
    pMemberExecutor: {
      memberRegistrationExecutorId: 0,
      memberRegistrationId: 0,
      firstName: "",
      middleName: "",
      lastName: "",
      brn: "",
      tin: "",
      genderId: 0,
      genderValue: "",
      dateOfBirth: "",
      mobileNo: "",
      emailId: "",
      personId: 0,
      peopleHubPersonId: 0,
      relationshipId: 0,
      relationshipValue: "",
      genderDescription: "",
      relationshipDescription: "",
      pExecutorDocument: {
        memberRegistrationExecutorDocumentId: 0,
        memberRegistrationExecutorId: 0,
        documentTypeId: 0,
        documentTypeValue: "",
        documentFileId: 0,
        isMandatory: "",
        documentTypeDescription: "",
        pdocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
        idoObjState: "",
        updateSeq: 0,
      },
      plstMemberExecutorDocuments: [],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      pExecutorAddress: {
        memberRegistrationAddressId: 0,
        memberRegistrationId: 0,
        line1: "",
        line2: "",
        city: "",
        province: "",
        island: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        countryId: 0,
        countryValue: "",
        refTypeId: 0,
        refTypeValue: "",
        idoObjState: "",
        updateSeq: 0,
        streetName: "",
        locality: "",
        postalAddress: "",
      },
      idoObjState: "",
      updateSeq: 0,
      pocrMemberExecutorDetail: {
        firstName: {
          value: "",
          confidence: "",
        },
        middleName: {
          value: "",
          confidence: "",
        },
        lastName: {
          value: "",
          confidence: "",
        },
        tin: {
          value: "",
          confidence: "",
        },
        birthRegNo: {
          value: "",
          confidence: "",
        },
        passportNo: {
          value: "",
          confidence: "",
        },
        dateOfBirth: {
          value: "",
          confidence: "",
        },
        gender: {
          value: "",
          confidence: "",
        },
      },
      preferredCommunicationId: 0,
      preferredCommunicationValue: "",
      fatherName: "",
      motherName: "",
      nationalityId: 0,
      nationalityValue: "",
    },
    pMemberAddress: {
      memberRegistrationAddressId: 0,
      memberRegistrationId: 0,
      line1: "",
      line2: "",
      city: "",
      province: "",
      island: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      countryId: 0,
      countryValue: "",
      refTypeId: 0,
      refTypeValue: "",
      idoObjState: "",
      updateSeq: 0,
      streetName: "",
      locality: "",
      postalAddress: "",
    },
    pMemberNominee: {
      memberRegistrationNomineeId: 0,
      memberRegistrationId: 0,
      firstName: "",
      middleName: "",
      lastName: "",
      dateOfBirth: "",
      brn: "",
      genderId: 0,
      genderValue: "",
      relationshipId: 0,
      relationshipValue: "",
      sharePercentage: "",
      personId: 0,
      peopleHubPersonId: 0,
      tin: "",
      genderDescription: "",
      relationshipDescription: "",
      pNomineeDocument: {
        memberRegistrationNomineeDocumentId: 0,
        memberRegistrationNomineeId: 0,
        documentTypeId: 0,
        documentTypeValue: "",
        documentFileId: 0,
        isMandatory: "",
        documentTypeDescription: "",
        pdocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
        idoObjState: "",
        updateSeq: 0,
      },
      plstMemberNomineeDocuments: [
        {
          memberRegistrationNomineeDocumentId: 0,
          memberRegistrationNomineeId: 0,
          documentTypeId: 0,
          documentTypeValue: "",
          documentFileId: 0,
          isMandatory: "",
          documentTypeDescription: "",
          pdocumentFile: {
            documentFileId: 0,
            fileType: "",
            fileSize: 0,
            relativePath: "",
            fileName: "",
            uploadbyFullName: "",
            istrFileContent: "",
            idoObjState: "",
            updateSeq: 0,
          },
          idoObjState: "",
          updateSeq: 0,
        },
      ],
      nomineeContactEmail: "",
      nomineeContactPhone: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      pNomineeAddress: {
        memberRegistrationAddressId: 0,
        memberRegistrationId: 0,
        line1: "",
        line2: "",
        city: "",
        province: "",
        island: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        countryId: 0,
        countryValue: "",
        refTypeId: 0,
        refTypeValue: "",
        idoObjState: "",
        updateSeq: 0,
      },
      idoObjState: "",
      updateSeq: 0,
      pocrMemberNomineeDetail: {
        firstName: {
          value: "",
          confidence: "",
        },
        middleName: {
          value: "",
          confidence: "",
        },
        lastName: {
          value: "",
          confidence: "",
        },
        tin: {
          value: "",
          confidence: "",
        },
        birthRegNo: {
          value: "",
          confidence: "",
        },
        passportNo: {
          value: "",
          confidence: "",
        },
        dateOfBirth: {
          value: "",
          confidence: "",
        },
        gender: {
          value: "",
          confidence: "",
        },
      },
      nationalityId: 0,
      nationalityValue: "",
    },
    plstMemberNominees: [],
    plstMemberDocuments: [],
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    funMsg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    promisWorkflowId: 0,
    fnpfId: "",
    documentContentId: 0,
    idoObjState: "",
    updateSeq: 0,
    pocrMemberDetail: {
      namePrefix: {
        value: "",
        confidence: "",
      },
      firstName: {
        value: "",
        confidence: "",
      },
      middleName: {
        value: "",
        confidence: "",
      },
      lastName: {
        value: "",
        confidence: "",
      },
      nameSuffix: {
        value: "",
        confidence: "",
      },
      tin: {
        value: "",
        confidence: "",
      },
      birthRegNo: {
        value: "",
        confidence: "",
      },
      passportNo: {
        value: "",
        confidence: "",
      },
      dateOfBirth: {
        value: "",
        confidence: "",
      },
      placeOfBirth: {
        value: "",
        confidence: "",
      },
      gender: {
        value: "",
        confidence: "",
      },
      fatherName: {
        value: "",
        confidence: "",
      },
      motherName: {
        value: "",
        confidence: "",
      },
    },
    politicallyExposedPerson: "",
    namePrefixValue: "",
    nameSuffixValue: "",
    religion: "",
    occupationValue: "",
    ocrJsonValue: "",
    memberRegistrationRefNo: "",
    submittedBy: "",
    submittedDate: "",
    orgName: "",
    memberTypeId: 0,
    memberTypeValue: "",
    memberTypeDescription: "",
    workPermitIssueDate: "",
    namePrefixId: 0,
    nameSuffixId: 0,
    occupationId: 0,
    protoWitnessMemberRegistrationDocument: {
      memberRegistrationDocumentId: 0,
      memberRegistrationId: 0,
      documentTypeId: 0,
      documentTypeValue: "",
      documentFileId: 0,
      isMandatory: "",
      documentTypeDescription: "",
      pdocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0,
      },
      idoObjState: "",
      updateSeq: 0,
    },
    witnessName: "",
    witnessDate: "",
    associateToPoliticallyExposedPerson: "",
    preferredCommunicationId: "",
    preferredCommunicationValue: "",
  };

  newNominee = {
    memberRegistrationNomineeId: 0,
    memberRegistrationId: 0,
    firstName: "",
    middleName: "",
    lastName: "",
    dateOfBirth: "",
    brn: "",
    genderId: 0,
    genderValue: "",
    relationshipId: 0,
    relationshipValue: "",
    sharePercentage: "",
    personId: 0,
    peopleHubPersonId: 0,
    tin: "",
    genderDescription: "",
    relationshipDescription: "",
    pNomineeDocument: {
      memberRegistrationNomineeDocumentId: 0,
      memberRegistrationNomineeId: 0,
      documentTypeId: 0,
      documentTypeValue: "",
      documentFileId: 0,
      isMandatory: "",
      documentTypeDescription: "",
      pdocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0,
      },
      idoObjState: "",
      updateSeq: 0,
    },
    plstMemberNomineeDocuments: [],
    nomineeContactEmail: "",
    nomineeContactPhone: "",
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    pNomineeAddress: {
      memberRegistrationAddressId: 0,
      memberRegistrationId: 0,
      line1: "",
      line2: "",
      city: "",
      province: "",
      island: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      countryId: 0,
      countryValue: "",
      refTypeId: 0,
      refTypeValue: "",
      idoObjState: "",
      updateSeq: 0,
    },
    idoObjState: "",
    updateSeq: 0,
    pocrMemberNomineeDetail: {
      firstName: {
        value: "",
        confidence: "",
      },
      middleName: {
        value: "",
        confidence: "",
      },
      lastName: {
        value: "",
        confidence: "",
      },
      tin: {
        value: "",
        confidence: "",
      },
      birthRegNo: {
        value: "",
        confidence: "",
      },
      passportNo: {
        value: "",
        confidence: "",
      },
      dateOfBirth: {
        value: "",
        confidence: "",
      },
      gender: {
        value: "",
        confidence: "",
      },
    },
    preferredCommunicationId: 0,
    preferredCommunicationValue: "",
    fatherName: "",
    motherName: "",
    nationalityId: 0,
    nationalityValue: "",
  };

  loadingTrue = false;
  btnClicked = false;
  errorTrue = false;

  memberParams = {
    MRNationality: [],
    MRGender: [],
    MREthnicity: [],
    MRCitizenship: [],
    MRMaritalStatus: [],
    MRNRelationship: [],
    MREXRelationship: [],
    MRCountry: [],
    DDLMemberType: [],
    MRPreferredCommunication: [],
    MRNamePreffix: [],
    MRNameSuffix: [],
    MROccupation: [],
    MRPhoneandEmail: [],
    MRPhoneandEmailandMail: [],
  };

  setAll(val) {
    this.btnClicked = val;
    this.loadingTrue = val;
    this.fullspinner.empty.next(val);
  }

  clearNewNominee() {
    this.newNominee = {
      memberRegistrationNomineeId: 0,
      memberRegistrationId: 0,
      firstName: "",
      middleName: "",
      lastName: "",
      dateOfBirth: "",
      brn: "",
      genderId: 0,
      genderValue: "",
      relationshipId: 0,
      relationshipValue: "",
      sharePercentage: "",
      personId: 0,
      peopleHubPersonId: 0,
      tin: "",
      genderDescription: "",
      relationshipDescription: "",
      pNomineeDocument: {
        memberRegistrationNomineeDocumentId: 0,
        memberRegistrationNomineeId: 0,
        documentTypeId: 0,
        documentTypeValue: "",
        documentFileId: 0,
        isMandatory: "",
        documentTypeDescription: "",
        pdocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
        idoObjState: "",
        updateSeq: 0,
      },
      plstMemberNomineeDocuments: [
        {
          memberRegistrationNomineeDocumentId: 0,
          memberRegistrationNomineeId: 0,
          documentTypeId: 0,
          documentTypeValue: "",
          documentFileId: 0,
          isMandatory: "",
          documentTypeDescription: "",
          pdocumentFile: {
            documentFileId: 0,
            fileType: "",
            fileSize: 0,
            relativePath: "",
            fileName: "",
            uploadbyFullName: "",
            istrFileContent: "",
            idoObjState: "",
            updateSeq: 0,
          },
          idoObjState: "",
          updateSeq: 0,
        },
      ],
      nomineeContactEmail: "",
      nomineeContactPhone: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      pNomineeAddress: {
        memberRegistrationAddressId: 0,
        memberRegistrationId: 0,
        line1: "",
        line2: "",
        city: "",
        province: "",
        island: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        countryId: 0,
        countryValue: "",
        refTypeId: 0,
        refTypeValue: "",
        idoObjState: "",
        updateSeq: 0,
      },
      idoObjState: "",
      updateSeq: 0,
      pocrMemberNomineeDetail: {
        firstName: {
          value: "",
          confidence: "",
        },
        middleName: {
          value: "",
          confidence: "",
        },
        lastName: {
          value: "",
          confidence: "",
        },
        tin: {
          value: "",
          confidence: "",
        },
        birthRegNo: {
          value: "",
          confidence: "",
        },
        passportNo: {
          value: "",
          confidence: "",
        },
        dateOfBirth: {
          value: "",
          confidence: "",
        },
        gender: {
          value: "",
          confidence: "",
        },
      },
      preferredCommunicationId: 0,
      preferredCommunicationValue: "",
      fatherName: "",
      motherName: "",
      nationalityId: 0,
      nationalityValue: "",
    };
  }

  clearNewMember() {
    this.newMember = {
      memberRegistrationId: 0,
      employerRefNo: "",
      orgId: 0,
      firstName: "",
      middleName: "",
      lastName: "",
      brn: "",
      tin: "",
      passportNo: "",
      dateOfBirth: "",
      placeOfBirth: "",
      nationalityId: 0,
      nationalityValue: "",
      genderId: 0,
      genderValue: "",
      fatherName: "",
      motherName: "",
      ethnicityId: 0,
      ethnicityValue: "",
      citizenshipId: 0,
      citizenshipValue: "",
      maritalStatusId: 0,
      maritalStatusValue: "",
      mobileNo: "",
      emailId: "",
      personId: 0,
      peopleHubPersonId: 0,
      optOutOfNominee: "",
      dateStartedWork: "",
      acceptDeclaration: "",
      statusId: 0,
      statusValue: "",
      transactionPin: "",
      declaration: "",
      nationalityDescription: "",
      genderDescription: "",
      ethnicityDescription: "",
      citizenshipDescription: "",
      maritalStatusDescription: "",
      statusDescription: "",
      createdDate: "",
      infoMsg: "",
      memberFullname: "",
      pMemberExecutor: {
        memberRegistrationExecutorId: 0,
        memberRegistrationId: 0,
        firstName: "",
        middleName: "",
        lastName: "",
        brn: "",
        tin: "",
        genderId: 0,
        genderValue: "",
        dateOfBirth: "",
        mobileNo: "",
        emailId: "",
        personId: 0,
        peopleHubPersonId: 0,
        relationshipId: 0,
        relationshipValue: "",
        genderDescription: "",
        relationshipDescription: "",
        pExecutorDocument: {
          memberRegistrationExecutorDocumentId: 0,
          memberRegistrationExecutorId: 0,
          documentTypeId: 0,
          documentTypeValue: "",
          documentFileId: 0,
          isMandatory: "",
          documentTypeDescription: "",
          pdocumentFile: {
            documentFileId: 0,
            fileType: "",
            fileSize: 0,
            relativePath: "",
            fileName: "",
            uploadbyFullName: "",
            istrFileContent: "",
            idoObjState: "",
            updateSeq: 0,
          },
          idoObjState: "",
          updateSeq: 0,
        },
        plstMemberExecutorDocuments: [],
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        pExecutorAddress: {
          memberRegistrationAddressId: 0,
          memberRegistrationId: 0,
          line1: "",
          line2: "",
          city: "",
          province: "",
          island: "",
          msg: {
            infoMessage: {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
            errorMessage: [
              {
                msgID: 0,
                msgType: 0,
                msgDescription: "",
              },
            ],
            hasError: true,
          },
          countryId: 0,
          countryValue: "",
          refTypeId: 0,
          refTypeValue: "",
          idoObjState: "",
          updateSeq: 0,
          streetName: "",
          locality: "",
          postalAddress: "",
        },
        idoObjState: "",
        updateSeq: 0,
        pocrMemberExecutorDetail: {
          firstName: {
            value: "",
            confidence: "",
          },
          middleName: {
            value: "",
            confidence: "",
          },
          lastName: {
            value: "",
            confidence: "",
          },
          tin: {
            value: "",
            confidence: "",
          },
          birthRegNo: {
            value: "",
            confidence: "",
          },
          passportNo: {
            value: "",
            confidence: "",
          },
          dateOfBirth: {
            value: "",
            confidence: "",
          },
          gender: {
            value: "",
            confidence: "",
          },
        },
        preferredCommunicationId: 0,
        preferredCommunicationValue: "",
        fatherName: "",
        motherName: "",
        nationalityId: 0,
        nationalityValue: "",
      },
      pMemberAddress: {
        memberRegistrationAddressId: 0,
        memberRegistrationId: 0,
        line1: "",
        line2: "",
        city: "",
        province: "",
        island: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        countryId: 0,
        countryValue: "",
        refTypeId: 0,
        refTypeValue: "",
        idoObjState: "",
        updateSeq: 0,
        streetName: "",
        locality: "",
        postalAddress: "",
      },
      pMemberNominee: {
        memberRegistrationNomineeId: 0,
        memberRegistrationId: 0,
        firstName: "",
        middleName: "",
        lastName: "",
        dateOfBirth: "",
        brn: "",
        genderId: 0,
        genderValue: "",
        relationshipId: 0,
        relationshipValue: "",
        sharePercentage: "",
        personId: 0,
        peopleHubPersonId: 0,
        tin: "",
        genderDescription: "",
        relationshipDescription: "",
        pNomineeDocument: {
          memberRegistrationNomineeDocumentId: 0,
          memberRegistrationNomineeId: 0,
          documentTypeId: 0,
          documentTypeValue: "",
          documentFileId: 0,
          isMandatory: "",
          documentTypeDescription: "",
          pdocumentFile: {
            documentFileId: 0,
            fileType: "",
            fileSize: 0,
            relativePath: "",
            fileName: "",
            uploadbyFullName: "",
            istrFileContent: "",
            idoObjState: "",
            updateSeq: 0,
          },
          idoObjState: "",
          updateSeq: 0,
        },
        plstMemberNomineeDocuments: [
          {
            memberRegistrationNomineeDocumentId: 0,
            memberRegistrationNomineeId: 0,
            documentTypeId: 0,
            documentTypeValue: "",
            documentFileId: 0,
            isMandatory: "",
            documentTypeDescription: "",
            pdocumentFile: {
              documentFileId: 0,
              fileType: "",
              fileSize: 0,
              relativePath: "",
              fileName: "",
              uploadbyFullName: "",
              istrFileContent: "",
              idoObjState: "",
              updateSeq: 0,
            },
            idoObjState: "",
            updateSeq: 0,
          },
        ],
        nomineeContactEmail: "",
        nomineeContactPhone: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        pNomineeAddress: {
          memberRegistrationAddressId: 0,
          memberRegistrationId: 0,
          line1: "",
          line2: "",
          city: "",
          province: "",
          island: "",
          msg: {
            infoMessage: {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
            errorMessage: [
              {
                msgID: 0,
                msgType: 0,
                msgDescription: "",
              },
            ],
            hasError: true,
          },
          countryId: 0,
          countryValue: "",
          refTypeId: 0,
          refTypeValue: "",
          idoObjState: "",
          updateSeq: 0,
        },
        idoObjState: "",
        updateSeq: 0,
        pocrMemberNomineeDetail: {
          firstName: {
            value: "",
            confidence: "",
          },
          middleName: {
            value: "",
            confidence: "",
          },
          lastName: {
            value: "",
            confidence: "",
          },
          tin: {
            value: "",
            confidence: "",
          },
          birthRegNo: {
            value: "",
            confidence: "",
          },
          passportNo: {
            value: "",
            confidence: "",
          },
          dateOfBirth: {
            value: "",
            confidence: "",
          },
          gender: {
            value: "",
            confidence: "",
          },
        },
        nationalityId: 0,
        nationalityValue: "",
      },
      plstMemberNominees: [],
      plstMemberDocuments: [],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      funMsg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      promisWorkflowId: 0,
      fnpfId: "",
      documentContentId: 0,
      idoObjState: "",
      updateSeq: 0,
      pocrMemberDetail: {
        namePrefix: {
          value: "",
          confidence: "",
        },
        firstName: {
          value: "",
          confidence: "",
        },
        middleName: {
          value: "",
          confidence: "",
        },
        lastName: {
          value: "",
          confidence: "",
        },
        nameSuffix: {
          value: "",
          confidence: "",
        },
        tin: {
          value: "",
          confidence: "",
        },
        birthRegNo: {
          value: "",
          confidence: "",
        },
        passportNo: {
          value: "",
          confidence: "",
        },
        dateOfBirth: {
          value: "",
          confidence: "",
        },
        placeOfBirth: {
          value: "",
          confidence: "",
        },
        gender: {
          value: "",
          confidence: "",
        },
        fatherName: {
          value: "",
          confidence: "",
        },
        motherName: {
          value: "",
          confidence: "",
        },
      },
      politicallyExposedPerson: "",
      namePrefixValue: "",
      nameSuffixValue: "",
      religion: "",
      occupationValue: "",
      ocrJsonValue: "",
      memberRegistrationRefNo: "",
      submittedBy: "",
      submittedDate: "",
      orgName: "",
      memberTypeId: 0,
      memberTypeValue: "",
      memberTypeDescription: "",
      workPermitIssueDate: "",
      namePrefixId: 0,
      nameSuffixId: 0,
      occupationId: 0,
      protoWitnessMemberRegistrationDocument: {
        memberRegistrationDocumentId: 0,
        memberRegistrationId: 0,
        documentTypeId: 0,
        documentTypeValue: "",
        documentFileId: 0,
        isMandatory: "",
        documentTypeDescription: "",
        pdocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
        idoObjState: "",
        updateSeq: 0,
      },
      witnessName: "",
      witnessDate: "",
      associateToPoliticallyExposedPerson: "",
      preferredCommunicationId: "",
      preferredCommunicationValue: "",
    };
  }
}
