import { Injectable } from "@angular/core";
import { BehaviorSubject, Observable } from "rxjs";

@Injectable({
  providedIn: "root",
})
export class CsAdjustmentService {
  DDL = {
    DDLMonthValue: [],
    DDLCSCodeValue: [],
  };
  protoentCSAdjustmentHeader = {
    errorStatusId: 0,
    actionStatusId: 0,
    actionStatusValue: "",
    csMonthId: 0,
    csMonthValue: "",
    contribMonthDescription: "",
    createdBy: "",
    createdDate: "",
    receivedDate: "",
    year: 0,
    toMemberRefNo: "",
    toMemberAccountId: 0,
    csMonthDescription: "",
    suppressWaringFlag: "",
    errorStatusValue: "",
    headerStatusDescription: "",
    adjHeaderId: 0,
    adjTypeId: 0,
    adjTypeValue: "",
    adjTypeDescription: "",
    userLoggedinId: "",
    memberRefNo: "",
    contHeaderId: 0,
    postedDate: "",
    totalAdjAmt: "",
    totalGrossSalary: "",
    headerStatusId: 0,
    headerStatusValue: "",
    memberAccountId: 0,
    lstprotoentCSAdjustmentDetail: [],
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    actionStatusDescription: "",
    protoentCSHeader: {
      csHeaderId: 0,
      scheduleTypeId: 0,
      scheduleTypeValue: "",
      orgId: 0,
      orgRefNo: "",
      csCode: "",
      csMonthId: 0,
      csMonthValue: "",
      year: 0,
      wages: "",
      receivedDate: "",
      dueDate: "",
      totalEmployee: 0,
      totalGrossSalary: "",
      penality: "",
      headerStatusId: 0,
      headerStatusValue: "",
      errorStatusId: 0,
      errorStatusValue: "",
      suppressWaringFlag: "",
      actionStatusId: 0,
      actionStatusValue: "",
      totalContributionAmount: "",
      lstprotoentCSDetail: [],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      csMonthDescription: "",
      headerStatusDescription: "",
      scheduleTypeDescription: "",
      userLoggedinId: "",
      wagesPaidMonthValue: "",
      wagesPaidMonthDescription: "",
      wagesPaidMonthId: 0,
      wagesPaidYear: 0,
      errorMessageCount: 0,
      warningMessageCount: 0,
      surpressWarning: "",
      infoMessageCount: 0,
      funMsg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      protoentCSDetail: {},
      employerName: "",
      tradeName: "",
      contributionSourceValue: "",
      totalNoOfReviewCsdetails: 0,
      totalNoOfCancelledCsdetails: 0,
      totalNoOfPostedCsdetails: 0,
      totalNoOfReversedCsdetails: 0,
      totalNoOfValidCsdetails: 0,
      totalNoOfSuspenseCsdetails: 0,
    },
    wagesYear: 0,
    wagesMonth: "",
    wagesMonthDescription: "",
    protoentCSAdjustmentDetail: {
      newOccupationValue: "",
      newPaymentFreqId: 0,
      newPaymentFreqValue: "",
      suspenseAccountFlag: "",
      detailStatusId: 0,
      detailStatusValue: "",
      errorStatusId: 0,
      errorStatusValue: "",
      suppressWaringFlag: "",
      calculateSurchargeFlag: "",
      memberAccountId: 0,
      memberAccountSubaccountId: 0,
      planContribRateId: 0,
      effectiveDate: "",
      generalAdjAmt: "",
      preservedAdjAmt: "",
      legacyMemberId: "",
      mataiSourceTable: "",
      accountSurffix: "",
      suspenseAccountReasonId: 0,
      suspenseAccountReasonValue: "",
      memberAccountTransactionId: 0,
      contribMonthValue: "",
      contribMonthId: 0,
      contribYear: 0,
      createdBy: "",
      modifiedBy: "",
      userLoggedinId: "",
      paymentFrequencyDescription: "",
      oldPaymentFreqValue: "",
      oldPaymentFreqId: 0,
      detailStatusDescription: "",
      newOccupationId: 0,
      adjDetailId: 0,
      adjHeaderId: 0,
      personId: 0,
      fnpfId: "",
      firstName: "",
      middleName: "",
      lastName: "",
      tin: "",
      dob: "",
      oldComplulsoryContri: "",
      newComplulsoryContri: "",
      oldEmployerAddContri: "",
      newEmployerAddContri: "",
      oldEmployeeAddContri: "",
      oldTotalContri: "",
      oldOccupationValue: "",
      oldOccupationId: 0,
      newEmploymentStatusDate: "",
      oldEmploymentStatusDate: "",
      newEmploymentStatusValue: "",
      newEmployeeAddContri: "",
      newEmploymentStatusId: 0,
      oldEmploymentStatusId: 0,
      newVoluntaryContri: "",
      oldVoluntaryContri: "",
      newMonthlyGrossSalary: "",
      oldMonthlyGrossSalary: "",
      newTotalContri: "",
      oldEmploymentStatusValue: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      newEmploymentStatusDescription: "",
      oldEmploymentStatusDescription: "",
      memberAccountStatusDescription: "",
      protoentPerson: {
        firstName: "",
        middleName: "",
        lastName: "",
        dateOfBirth: "",
        genderId: 0,
        genderValue: "",
        genderDescription: "",
        fatherName: "",
        motherName: "",
        fnpfNo: "",
        tin: "",
        passportNo: "",
        personId: 0,
        mobileNo: "",
        emailId: "",
        citizenshipId: 0,
        citizenshipValue: "",
        citizenshipDescription: "",
        ethnicityId: 0,
        ethnicityValue: "",
        ethnicityDescription: "",
        nationalId: 0,
        nationalValue: "",
        nationalDescription: "",
        maritalStatusId: 0,
        maritalStatusValue: "",
        maritalStatusDescription: "",
        personStatusId: 0,
        personStatusValue: "",
        personStatusDescription: "",
        peopleHubId: 0,
        errorStatusId: 0,
        errorStatusValue: "",
        actionStatusId: 0,
        actionStatusValue: "",
        interfaceStatusId: 0,
        interfaceStatusValue: "",
        hotlistFlag: "",
        suppressWarningsFlag: "",
        duplicateFlag: "",
        cAndFNotificationFlag: "",
        birthRegNo: "",
        employmentStartDate: "",
        employmentEndDate: "",
        lastContributionMonthYear: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
      },
      memberStatusDescription: "",
      employeeContriRate: "",
      employerContriRate: "",
      funMsg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [],
        hasError: true,
      },
      errorMessageCount: 0,
      warningMessageCount: 0,
      infoMessageCount: 0,
      updateSeq: 0,
    },
    lstprotoadjustmentdocuments: [],
    blnIsCreatedByLoggedinUser: false,
    blnIsEditable: false,
    funMsg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [],
      hasError: true,
    },
    errorMessageCount: 0,
    warningMessageCount: 0,
    infoMessageCount: 0,
    updateSeq: 0,
  };
  newClicked = new BehaviorSubject<boolean>(false);

  constructor() {}
  clearData() {
    console.log("clear data called");
    this.protoentCSAdjustmentHeader = {
      errorStatusId: 0,
      actionStatusId: 0,
      actionStatusValue: "",
      csMonthId: 0,
      csMonthValue: "",
      contribMonthDescription: "",
      createdBy: "",
      createdDate: "",
      receivedDate: "",
      year: 0,
      toMemberRefNo: "",
      toMemberAccountId: 0,
      csMonthDescription: "",
      suppressWaringFlag: "",
      errorStatusValue: "",
      headerStatusDescription: "",
      adjHeaderId: 0,
      adjTypeId: 0,
      adjTypeValue: "",
      adjTypeDescription: "",
      userLoggedinId: "",
      memberRefNo: "",
      contHeaderId: 0,
      postedDate: "",
      totalAdjAmt: "",
      totalGrossSalary: "",
      headerStatusId: 0,
      headerStatusValue: "",
      memberAccountId: 0,
      lstprotoentCSAdjustmentDetail: [],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      actionStatusDescription: "",
      protoentCSHeader: {
        csHeaderId: 0,
        scheduleTypeId: 0,
        scheduleTypeValue: "",
        orgId: 0,
        orgRefNo: "",
        csCode: "",
        csMonthId: 0,
        csMonthValue: "",
        year: 0,
        wages: "",
        receivedDate: "",
        dueDate: "",
        totalEmployee: 0,
        totalGrossSalary: "",
        penality: "",
        headerStatusId: 0,
        headerStatusValue: "",
        errorStatusId: 0,
        errorStatusValue: "",
        suppressWaringFlag: "",
        actionStatusId: 0,
        actionStatusValue: "",
        totalContributionAmount: "",
        lstprotoentCSDetail: [],
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        csMonthDescription: "",
        headerStatusDescription: "",
        scheduleTypeDescription: "",
        userLoggedinId: "",
        wagesPaidMonthValue: "",
        wagesPaidMonthDescription: "",
        wagesPaidMonthId: 0,
        wagesPaidYear: 0,
        errorMessageCount: 0,
        warningMessageCount: 0,
        surpressWarning: "",
        infoMessageCount: 0,
        funMsg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        protoentCSDetail: {},
        employerName: "",
        tradeName: "",
        contributionSourceValue: "",
        totalNoOfReviewCsdetails: 0,
        totalNoOfCancelledCsdetails: 0,
        totalNoOfPostedCsdetails: 0,
        totalNoOfReversedCsdetails: 0,
        totalNoOfValidCsdetails: 0,
        totalNoOfSuspenseCsdetails: 0,
      },
      wagesYear: 0,
      wagesMonth: "",
      wagesMonthDescription: "",
      protoentCSAdjustmentDetail: {
        newOccupationValue: "",
        newPaymentFreqId: 0,
        newPaymentFreqValue: "",
        suspenseAccountFlag: "",
        detailStatusId: 0,
        detailStatusValue: "",
        errorStatusId: 0,
        errorStatusValue: "",
        suppressWaringFlag: "",
        calculateSurchargeFlag: "",
        memberAccountId: 0,
        memberAccountSubaccountId: 0,
        planContribRateId: 0,
        effectiveDate: "",
        generalAdjAmt: "",
        preservedAdjAmt: "",
        legacyMemberId: "",
        mataiSourceTable: "",
        accountSurffix: "",
        suspenseAccountReasonId: 0,
        suspenseAccountReasonValue: "",
        memberAccountTransactionId: 0,
        contribMonthValue: "",
        contribMonthId: 0,
        contribYear: 0,
        createdBy: "",
        modifiedBy: "",
        userLoggedinId: "",
        paymentFrequencyDescription: "",
        oldPaymentFreqValue: "",
        oldPaymentFreqId: 0,
        detailStatusDescription: "",
        newOccupationId: 0,
        adjDetailId: 0,
        adjHeaderId: 0,
        personId: 0,
        fnpfId: "",
        firstName: "",
        middleName: "",
        lastName: "",
        tin: "",
        dob: "",
        oldComplulsoryContri: "",
        newComplulsoryContri: "",
        oldEmployerAddContri: "",
        newEmployerAddContri: "",
        oldEmployeeAddContri: "",
        oldTotalContri: "",
        oldOccupationValue: "",
        oldOccupationId: 0,
        newEmploymentStatusDate: "",
        oldEmploymentStatusDate: "",
        newEmploymentStatusValue: "",
        newEmployeeAddContri: "",
        newEmploymentStatusId: 0,
        oldEmploymentStatusId: 0,
        newVoluntaryContri: "",
        oldVoluntaryContri: "",
        newMonthlyGrossSalary: "",
        oldMonthlyGrossSalary: "",
        newTotalContri: "",
        oldEmploymentStatusValue: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        newEmploymentStatusDescription: "",
        oldEmploymentStatusDescription: "",
        memberAccountStatusDescription: "",
        protoentPerson: {
          firstName: "",
          middleName: "",
          lastName: "",
          dateOfBirth: "",
          genderId: 0,
          genderValue: "",
          genderDescription: "",
          fatherName: "",
          motherName: "",
          fnpfNo: "",
          tin: "",
          passportNo: "",
          personId: 0,
          mobileNo: "",
          emailId: "",
          citizenshipId: 0,
          citizenshipValue: "",
          citizenshipDescription: "",
          ethnicityId: 0,
          ethnicityValue: "",
          ethnicityDescription: "",
          nationalId: 0,
          nationalValue: "",
          nationalDescription: "",
          maritalStatusId: 0,
          maritalStatusValue: "",
          maritalStatusDescription: "",
          personStatusId: 0,
          personStatusValue: "",
          personStatusDescription: "",
          peopleHubId: 0,
          errorStatusId: 0,
          errorStatusValue: "",
          actionStatusId: 0,
          actionStatusValue: "",
          interfaceStatusId: 0,
          interfaceStatusValue: "",
          hotlistFlag: "",
          suppressWarningsFlag: "",
          duplicateFlag: "",
          cAndFNotificationFlag: "",
          birthRegNo: "",
          employmentStartDate: "",
          employmentEndDate: "",
          lastContributionMonthYear: "",
          msg: {
            infoMessage: {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
            errorMessage: [
              {
                msgID: 0,
                msgType: 0,
                msgDescription: "",
              },
            ],
            hasError: true,
          },
        },
        memberStatusDescription: "",
        employeeContriRate: "",
        employerContriRate: "",
        funMsg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [],
          hasError: true,
        },
        errorMessageCount: 0,
        warningMessageCount: 0,
        infoMessageCount: 0,
        updateSeq: 0,
      },
      blnIsCreatedByLoggedinUser: false,
      blnIsEditable: false,
      lstprotoadjustmentdocuments: [],
      funMsg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [],
        hasError: true,
      },
      errorMessageCount: 0,
      warningMessageCount: 0,
      infoMessageCount: 0,
      updateSeq: 0,
    };
  }
  adjustmentHeaderId = 0;
  adjustmentDetailId = 0;
  createdata() {
    this.protoentCSAdjustmentHeader.protoentCSAdjustmentDetail = {
      newOccupationValue: "",
      newPaymentFreqId: 0,
      newPaymentFreqValue: "",
      suspenseAccountFlag: "",
      detailStatusId: 0,
      detailStatusValue: "",
      errorStatusId: 0,
      errorStatusValue: "",
      suppressWaringFlag: "",
      calculateSurchargeFlag: "",
      memberAccountId: 0,
      memberAccountSubaccountId: 0,
      planContribRateId: 0,
      effectiveDate: "",
      generalAdjAmt: "",
      preservedAdjAmt: "",
      legacyMemberId: "",
      mataiSourceTable: "",
      accountSurffix: "",
      suspenseAccountReasonId: 0,
      suspenseAccountReasonValue: "",
      memberAccountTransactionId: 0,
      contribMonthValue: "",
      contribMonthId: 0,
      contribYear: 0,
      createdBy: "",
      modifiedBy: "",
      userLoggedinId: "",
      paymentFrequencyDescription: "",
      oldPaymentFreqValue: "",
      oldPaymentFreqId: 0,
      detailStatusDescription: "",
      newOccupationId: 0,
      adjDetailId: 0,
      adjHeaderId: 0,
      personId: 0,
      fnpfId: "",
      firstName: "",
      middleName: "",
      lastName: "",
      tin: "",
      dob: "",
      oldComplulsoryContri: "",
      newComplulsoryContri: "",
      oldEmployerAddContri: "",
      newEmployerAddContri: "",
      oldEmployeeAddContri: "",
      oldTotalContri: "",
      oldOccupationValue: "",
      oldOccupationId: 0,
      newEmploymentStatusDate: "",
      oldEmploymentStatusDate: "",
      newEmploymentStatusValue: "",
      newEmployeeAddContri: "",
      newEmploymentStatusId: 0,
      oldEmploymentStatusId: 0,
      newVoluntaryContri: "",
      oldVoluntaryContri: "",
      newMonthlyGrossSalary: "",
      oldMonthlyGrossSalary: "",
      newTotalContri: "",
      oldEmploymentStatusValue: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      newEmploymentStatusDescription: "",
      oldEmploymentStatusDescription: "",
      memberAccountStatusDescription: "",
      protoentPerson: {
        firstName: "",
        middleName: "",
        lastName: "",
        dateOfBirth: "",
        genderId: 0,
        genderValue: "",
        genderDescription: "",
        fatherName: "",
        motherName: "",
        fnpfNo: "",
        tin: "",
        passportNo: "",
        personId: 0,
        mobileNo: "",
        emailId: "",
        citizenshipId: 0,
        citizenshipValue: "",
        citizenshipDescription: "",
        ethnicityId: 0,
        ethnicityValue: "",
        ethnicityDescription: "",
        nationalId: 0,
        nationalValue: "",
        nationalDescription: "",
        maritalStatusId: 0,
        maritalStatusValue: "",
        maritalStatusDescription: "",
        personStatusId: 0,
        personStatusValue: "",
        personStatusDescription: "",
        peopleHubId: 0,
        errorStatusId: 0,
        errorStatusValue: "",
        actionStatusId: 0,
        actionStatusValue: "",
        interfaceStatusId: 0,
        interfaceStatusValue: "",
        hotlistFlag: "",
        suppressWarningsFlag: "",
        duplicateFlag: "",
        cAndFNotificationFlag: "",
        birthRegNo: "",
        employmentStartDate: "",
        employmentEndDate: "",
        lastContributionMonthYear: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
      },
      memberStatusDescription: "",
      employeeContriRate: "",
      employerContriRate: "",
      funMsg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [],
        hasError: true,
      },
      errorMessageCount: 0,
      warningMessageCount: 0,
      infoMessageCount: 0,
      updateSeq: 0,
    };
  }
}
