import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class ComplianceCertificateService {
  DDL = {
    DDLMonthValue: [],
  };

  compliancecertificate = {
    iProtoentCompliance: {
      orgId: 0,
      orgRefNo: "",
      employerStatus: "",
      usingEmployerPortal: "",
      lastContributionSubmittedThroughEmployersPortal: "",
      lastContributionSubmittedAndPaid: "",
      debtExists: "",
      unpaidPenalities: "",
      unresolvedSuspense: "",
      unclaimedFundsExists: "",
      undistributedFundsExists: "",
      accruals: "",
      complaints: "",
      fromYear: 0,
      toYear: 0,
      showGeneratebtn: "",
      oneYearCompliance: "",
      conditionalCompliance: "",
      orgName: "",
      generatedDate: "",
      tradeName: "",
      expiryDate: "",
      conditionalvaliditydate: "",
      alreadyGenerated: "",
      postaladdress: "",
      complianceRefNo: "",
      dtmGeneratedDate: "",
      dtmExpiryDate: "",
      qrCodeBase64: "",
      iblShowGeneratebtn: "",
      lstmessage: [
        {
          messageDescription: "",
          messageCode: 0,
        },
      ],
      isValidComplianceLetter: "",
      isInspectionExist: "",
    },
    iprotoentOrganization: {
      orgId: 0,
      businessName: "",
      tradeName: "",
      orgRefNo: "",
      tin: "",
      businessRegNo: "",
      businessRegDate: "",
      businessLicenseNo: "",
      fircNo: "",
      natureOfBusiness: "",
      orgStatusId: 0,
      orgStatusValue: "",
      orgStatusDescription: "",
      overseasOrg: true,
      lstOrgContact: [],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      lstEntAdderss: [],
      lstEntCommunication: [],
      protoentAddress: {
        personId: 0,
        orgId: 0,
        addressId: 0,
        line1: "",
        line2: "",
        city: "",
        province: "",
        source: "",
        addressType: "",
        status: "",
        countryValue: "",
        countryDescription: "",
        island: "",
        createdDate: "",
        addressTypeDescription: "",
      },
      protoentOrgCommunication: {
        orgCommunicationId: 0,
        orgId: 0,
        orgReFNo: "",
        orgCommunicationTypeId: 0,
        orgCommunicationTypeValue: "",
        orgCommunicationTypeDescription: "",
        orgCommunicationStatusId: 0,
        orgCommunicationStatusValue: "",
        orgCommunicationStatusDescription: "",
        communicationDetail: "",
      },
    },
    iprotoentPortalUser: {
      lastLoginDate: "",
      successfulLoginAttempts: 0,
      lockCount: 0,
      passwordLastChangedDate: "",
      passwordResetFlag: "",
      lastEmailSentDate: "",
      lastLockedDate: "",
      unsuccessfulLoginAttempts: 0,
      passwordExpiryDate: "",
      statusValue: "",
      statusDescription: "",
      statusId: 0,
      password: "",
      userId: "",
      receivedDate: "",
      personId: 0,
      employerPortalAccessId: 0,
      currentLoginDate: "",
      workEmailAddress: "",
    },
    ilstprotoentCSHeader: [],
    ilstProtoentViewInvoice: [],
    ilstProtoentSuspense: [],
    ilstProtoentUnclaim: [],
    ilstprotoentReceiptDetail: [],
    ilstProtoentCreditMemo: [],
    ilstprotoentPortalUser: [],
    ilstComplaints: [],
    ilstlastContributionThroughPortal: [],
    ilstlstContributionSubmittedandpaid: [],
    ilstAccurals: [],
    ilstDept: [],
    ilstPenalties: [],
    ilstProtoInspectionCase: [],
  };

  clearData() {
    this.compliancecertificate = {
      iProtoentCompliance: {
        orgId: 0,
        orgRefNo: "",
        employerStatus: "",
        usingEmployerPortal: "",
        lastContributionSubmittedThroughEmployersPortal: "",
        lastContributionSubmittedAndPaid: "",
        debtExists: "",
        unpaidPenalities: "",
        unresolvedSuspense: "",
        unclaimedFundsExists: "",
        undistributedFundsExists: "",
        accruals: "",
        complaints: "",
        fromYear: 0,
        toYear: 0,
        showGeneratebtn: "",
        oneYearCompliance: "",
        conditionalCompliance: "",
        orgName: "",
        generatedDate: "",
        tradeName: "",
        expiryDate: "",
        conditionalvaliditydate: "",
        alreadyGenerated: "",
        postaladdress: "",
        complianceRefNo: "",
        dtmGeneratedDate: "",
        dtmExpiryDate: "",
        qrCodeBase64: "",
        iblShowGeneratebtn: "",
        lstmessage: [
          {
            messageDescription: "",
            messageCode: 0,
          },
        ],
        isValidComplianceLetter: "",
        isInspectionExist: "",
      },
      iprotoentOrganization: {
        orgId: 0,
        businessName: "",
        tradeName: "",
        orgRefNo: "",
        tin: "",
        businessRegNo: "",
        businessRegDate: "",
        businessLicenseNo: "",
        fircNo: "",
        natureOfBusiness: "",
        orgStatusId: 0,
        orgStatusValue: "",
        orgStatusDescription: "",
        overseasOrg: true,
        lstOrgContact: [],
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        lstEntAdderss: [],
        lstEntCommunication: [],
        protoentAddress: {
          personId: 0,
          orgId: 0,
          addressId: 0,
          line1: "",
          line2: "",
          city: "",
          province: "",
          source: "",
          addressType: "",
          status: "",
          countryValue: "",
          countryDescription: "",
          island: "",
          createdDate: "",
          addressTypeDescription: "",
        },
        protoentOrgCommunication: {
          orgCommunicationId: 0,
          orgId: 0,
          orgReFNo: "",
          orgCommunicationTypeId: 0,
          orgCommunicationTypeValue: "",
          orgCommunicationTypeDescription: "",
          orgCommunicationStatusId: 0,
          orgCommunicationStatusValue: "",
          orgCommunicationStatusDescription: "",
          communicationDetail: "",
        },
      },
      iprotoentPortalUser: {
        lastLoginDate: "",
        successfulLoginAttempts: 0,
        lockCount: 0,
        passwordLastChangedDate: "",
        passwordResetFlag: "",
        lastEmailSentDate: "",
        lastLockedDate: "",
        unsuccessfulLoginAttempts: 0,
        passwordExpiryDate: "",
        statusValue: "",
        statusDescription: "",
        statusId: 0,
        password: "",
        userId: "",
        receivedDate: "",
        personId: 0,
        employerPortalAccessId: 0,
        currentLoginDate: "",
        workEmailAddress: "",
      },
      ilstprotoentCSHeader: [],
      ilstProtoentViewInvoice: [],
      ilstProtoentSuspense: [],
      ilstProtoentUnclaim: [],
      ilstprotoentReceiptDetail: [],
      ilstProtoentCreditMemo: [],
      ilstprotoentPortalUser: [],
      ilstComplaints: [],
      ilstlastContributionThroughPortal: [],
      ilstlstContributionSubmittedandpaid: [],
      ilstAccurals: [],
      ilstDept: [],
      ilstPenalties: [],
      ilstProtoInspectionCase: [],
    };
  }
  constructor() {}
}
