import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class newcontributionservice {
  createdetail = {
    csHeaderId: 0,
    scheduleTypeId: 0,
    scheduleTypeValue: "",
    orgId: 0,
    orgRefNo: "",
    csCode: "",
    csMonthId: 0,
    csMonthValue: "",
    year: 0,
    wages: "",
    receivedDate: "",
    dueDate: "",
    totalEmployee: 0,
    totalGrossSalary: "",
    penality: "",
    headerStatusId: 0,
    headerStatusValue: "",
    errorStatusId: 0,
    errorStatusValue: "",
    suppressWaringFlag: "",
    actionStatusId: 0,
    actionStatusValue: "",
    totalContributionAmount: "",
    lstprotoentCSDetail: [],
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    csMonthDescription: "",
    headerStatusDescription: "",
    scheduleTypeDescription: "",
    userLoggedinId: "",
    wagesPaidMonthValue: "",
    wagesPaidMonthDescription: "",
    wagesPaidMonthId: 0,
    wagesPaidYear: 0,
    errorMessageCount: 0,
    warningMessageCount: 0,
    surpressWarning: "",
    infoMessageCount: 0,
    funMsg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    protoentCSDetail: {
      csDetailId: 0,
      csHeaderId: 0,
      fnpfNo: "",
      firstName: "",
      middleName: "",
      lastName: "",
      complulsoryContri: "",
      employerAddContri: "",
      employeeAddContri: "",
      totalContri: "",
      grossSalary: "",
      voluntaryContri: "",
      suspenseAccountFlag: "",
      detailStatusId: 0,
      detailStatusValue: "",
      errorStatusId: 0,
      errorStatusValue: "",
      suppressWaringFlag: "",
      personId: 0,
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      tin: "",
      dob: "",
      userLoggedinId: "",
      employmentStatusValue: "",
      employmentStatusDescription: "",
      employmentStatusDate: "",
      paymentFrequencyValue: "",
      paymentFrequencyDescription: "",
      employeeContriRate: "",
      employerContriRate: "",
      occupationCode: "",
      detailStatusDescription: "",
      errorMessageCount: 0,
      warningMessageCount: 0,
      infoMessageCount: 0,
      payrollName: "",
      payrollTin: "",
      occupation: "",
      memberAccountId: 0,
      memberAccountSubaccountId: 0,
      updateSeq: 0,
    },
    employerName: "",
    tradeName: "",
    contributionSourceValue: "",
    totalNoOfReviewCsdetails: 0,
    totalNoOfCancelledCsdetails: 0,
    totalNoOfPostedCsdetails: 0,
    totalNoOfReversedCsdetails: 0,
    totalNoOfValidCsdetails: 0,
    totalNoOfSuspenseCsdetails: 0,
    iAdjCount: 0,
    updateSeq: 0,
  };

  createemployee = {
    csDetailId: 0,
    csHeaderId: 0,
    fnpfNo: "",
    firstName: "",
    middleName: "",
    lastName: "",
    complulsoryContri: "",
    employerAddContri: "",
    employeeAddContri: "",
    totalContri: "",
    grossSalary: "",
    voluntaryContri: "",
    suspenseAccountFlag: "",
    detailStatusId: 0,
    detailStatusValue: "",
    errorStatusId: 0,
    errorStatusValue: "",
    suppressWaringFlag: "",
    personId: 0,
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    tin: "",
    dob: "",
    userLoggedinId: "",
    employmentStatusValue: "",
    employmentStatusDescription: "",
    employmentStatusDate: "",
    paymentFrequencyValue: "",
    paymentFrequencyDescription: "",
    employeeContriRate: "",
    employerContriRate: "",
    occupationCode: "",
    detailStatusDescription: "",
    errorMessageCount: 0,
    warningMessageCount: 0,
    infoMessageCount: 0,
    payrollName: "",
    payrollTin: "",
    occupation: "",
    memberAccountId: 0,
    memberAccountSubaccountId: 0,
    updateSeq: 0,
  };

  DDL: any = {
    DDLMonthValue: [],
    DDLEmploymentStatusValue: [],
    DDLPaymentFrequencyValue: [],
    DDLCSCodeValue: [],
    DDLCSHeaderStatusValue: [],
    DDLCSDetailOccupationCode: [],
  };
  constructor() {}

  clearData() {
    this.createdetail = {
      csHeaderId: 0,
      scheduleTypeId: 0,
      scheduleTypeValue: "",
      orgId: 0,
      orgRefNo: "",
      csCode: "",
      csMonthId: 0,
      csMonthValue: "",
      year: 0,
      wages: "",
      receivedDate: "",
      dueDate: "",
      totalEmployee: 0,
      totalGrossSalary: "",
      penality: "",
      headerStatusId: 0,
      headerStatusValue: "",
      errorStatusId: 0,
      errorStatusValue: "",
      suppressWaringFlag: "",
      actionStatusId: 0,
      actionStatusValue: "",
      totalContributionAmount: "",
      lstprotoentCSDetail: [],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      csMonthDescription: "",
      headerStatusDescription: "",
      scheduleTypeDescription: "",
      userLoggedinId: "",
      wagesPaidMonthValue: "",
      wagesPaidMonthDescription: "",
      wagesPaidMonthId: 0,
      wagesPaidYear: 0,
      errorMessageCount: 0,
      warningMessageCount: 0,
      surpressWarning: "",
      infoMessageCount: 0,
      funMsg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      protoentCSDetail: {
        csDetailId: 0,
        csHeaderId: 0,
        fnpfNo: "",
        firstName: "",
        middleName: "",
        lastName: "",
        complulsoryContri: "",
        employerAddContri: "",
        employeeAddContri: "",
        totalContri: "",
        grossSalary: "",
        voluntaryContri: "",
        suspenseAccountFlag: "",
        detailStatusId: 0,
        detailStatusValue: "",
        errorStatusId: 0,
        errorStatusValue: "",
        suppressWaringFlag: "",
        personId: 0,
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        tin: "",
        dob: "",
        userLoggedinId: "",
        employmentStatusValue: "",
        employmentStatusDescription: "",
        employmentStatusDate: "",
        paymentFrequencyValue: "",
        paymentFrequencyDescription: "",
        employeeContriRate: "",
        employerContriRate: "",
        occupationCode: "",
        detailStatusDescription: "",
        errorMessageCount: 0,
        warningMessageCount: 0,
        infoMessageCount: 0,
        payrollName: "",
        payrollTin: "",
        occupation: "",
        memberAccountId: 0,
        memberAccountSubaccountId: 0,
        updateSeq: 0,
      },
      employerName: "",
      tradeName: "",
      contributionSourceValue: "",
      totalNoOfReviewCsdetails: 0,
      totalNoOfCancelledCsdetails: 0,
      totalNoOfPostedCsdetails: 0,
      totalNoOfReversedCsdetails: 0,
      totalNoOfValidCsdetails: 0,
      totalNoOfSuspenseCsdetails: 0,
      iAdjCount: 0,
      updateSeq: 0,
    };
  }
}
