import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class TimePaymentRequestService {
  DDL = {
    StatusValue: [],
  };
  constructor() { }
  clearData() {
    this.TimePaymentPlan = {
      timePaymentPlanRequestId: 0,
      organizationId: 0,
      requestRefNo: "",
      requestedDate: "",
      requestedByContactId: 0,
      submitedDate: "",
      submitedByContactId: 0,
      idoObjState: "",
      updateSeq: 0,
      tAndCFlag: "",
      fileName: "",
      formContent: "",
      timePaymentRequestStatusId: 0,
      timePaymentRequestStatusValue: "",
      timePaymentRequestStatusDescription: "",
      istrtermsandconditions: "",
      plsProtoTimePaymentPlanRequestInvoice: [
        {
          timePaymentPlanRequestInvoiceId: 0,
          timePaymentPlanRequestId: 0,
          invoiceId: 0,
          invoiceNo: "",
          invoiceAmount: "",
          invoicePaidAmount: "",
          invoiceBalanceAmount: "",
          csMonth: 0,
          csYear: 0,
          csCodeId: 0,
          invoiceTypeId: 0,
          invoiceTypeValue: "",
          includedInRequest: "",
          idoObjState: "",
          updateSeq: 0,
          invoiceStatusId: 0,
          invoiceStatusValue: "",
          invoiceStatusDescription: "",
          invoiceTypeDescription: "",
        },
      ],

      plstTimPaymentDocumentTypes: [{
        timePaymentPlanRequestDocumentId: 0,
        timePaymentPlanRequestId: 0,
        documentTypeId: 0,
        documentTypeValue: "",
        documentFileId: 0,
        isMandatory: "",
        idoObjState: "",
        updateSeq: 0,
        pDocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },

      }],

      // protoTimePaymentPlanRequestDocument: {
      //   timePaymentPlanRequestDocumentId: 0,
      //   timePaymentPlanRequestId: 0,
      //   documentTypeId: 0,
      //   documentTypeValue: "",
      //   documentFileId: 0,
      //   isMandatory: "",
      //   idoObjState: "",
      //   updateSeq: 0,
      //   pDocumentFile: {
      //     documentFileId: 0,
      //     fileType: "",
      //     fileSize: 0,
      //     relativePath: "",
      //     fileName: "",
      //     istrFileContent: "",
      //     idoObjState: "",
      //     updateSeq: 0,
      //   },
      // },
    };
  }

  TimePaymentPlan = {
    timePaymentPlanRequestId: 0,
    organizationId: 0,
    requestRefNo: "",
    requestedDate: "",
    requestedByContactId: 0,
    submitedDate: "",
    submitedByContactId: 0,
    idoObjState: "",
    updateSeq: 0,
    tAndCFlag: "",
    fileName: "",
    formContent: "",
    timePaymentRequestStatusId: 0,
    timePaymentRequestStatusValue: "",
    timePaymentRequestStatusDescription: "",
    istrtermsandconditions : "",
    plsProtoTimePaymentPlanRequestInvoice: [
      {
        timePaymentPlanRequestInvoiceId: 0,
        timePaymentPlanRequestId: 0,
        invoiceId: 0,
        invoiceNo: "",
        invoiceAmount: "",
        invoicePaidAmount: "",
        invoiceBalanceAmount: "",
        csMonth: 0,
        csYear: 0,
        csCodeId: 0,
        invoiceTypeId: 0,
        invoiceTypeValue: "",
        includedInRequest: "",
        idoObjState: "",
        updateSeq: 0,
        invoiceStatusId: 0,
        invoiceStatusValue: "",
        invoiceStatusDescription: "",
        invoiceTypeDescription: "",
      },
    ],

    plstTimPaymentDocumentTypes: [{
      timePaymentPlanRequestDocumentId: 0,
      timePaymentPlanRequestId: 0,
      documentTypeId: 0,
      documentTypeValue: "",
      documentFileId: 0,
      isMandatory: "",
      idoObjState: "",
      updateSeq: 0,
      pDocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0,
      },

    }],
    // protoTimePaymentPlanRequestDocument: {
    //   timePaymentPlanRequestDocumentId: 0,
    //   timePaymentPlanRequestId: 0,
    //   documentTypeId: 0,
    //   documentTypeValue: "",
    //   documentFileId: 0,
    //   isMandatory: "",
    //   idoObjState: "",
    //   updateSeq: 0,
    //   pDocumentFile: {
    //     documentFileId: 0,
    //     fileType: "",
    //     fileSize: 0,
    //     relativePath: "",
    //     fileName: "",
    //     istrFileContent: "",
    //     idoObjState: "",
    //     updateSeq: 0,
    //   },
    // },
  };
}
