import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class SuspenseService {
  DDL = {
    DDLMonthValue: [],
    DDLStatusValue: [],
  };

  constructor() {}
  suspense = {
    suspenseAccountId: 0,
    suspenseDate: "",
    suspenseSourceId: 0,
    suspenseSourceDescription: "",
    suspenseSourceValue: "",
    suspenseSourceRefId: 0,
    suspenseReasonId: 0,
    suspenseReasonDescription: "",
    suspenseReasonValue: "",
    suspenseStatusId: 0,
    suspenseStatusDescription: "",
    suspenseStatusValue: "",
    actionStatusId: 0,
    actionStatusDescription: "",
    actionStatusValue: "",
    suspenseAmt: "",
    orgId: 0,
    fnpfId: "",
    personId: 0,
    memberAccountId: 0,
    postedDate: "",
    errorStatusId: 0,
    errorStatusDescription: "",
    errorStatusValue: "",
    suppressWarningsFlag: "",
    resolvedDate: "",
    firstName: "",
    middleName: "",
    lastName: "",
    tin: "",
    birthDate: "",
    canNotIdentifyFlag: "",
    withdrawalApplicationId: 0,
    creditMemoId: 0,
    creditMemoCreatedDate: "",
    includeInDebtFlag: "",
    memberFullName: "",
    csMonth: "",
    csYear: 0,
    mobileNo: "",
    accountTypeDescription: "",
    accountStatusDescription: "",
    csMonthDescription: "",
    promisMemberFullName: "",
    isRefund: false,
    memberAccountStartDate: "",
    memberAccountEndDate: "",
    protoSuspenseRefundForm: {
      suspenseRefundFormId: 0,
      suspenseId: 0,
      organizationId: 0,
      orgContactId: 0,
      uploadedFileName: "",
      uploadedDate: "",
      contentServerDocId: 0,
      communicationId: 0,
      pdocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0,
      },
      documentFileId: 0,
    },

    protoPhotoIdentity: {
      suspenseRefundFormId: 0,
      suspenseId: 0,
      organizationId: 0,
      orgContactId: 0,
      uploadedFileName: "",
      uploadedDate: "",
      contentServerDocId: 0,
      communicationId: 0,
      pdocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0,
      },
      documentFileId: 0,
    },
    wagesMonth: "",
    wagesYear: 0,
    wagesMonthDescription: "",
    updateSeq: 0,
  };

  clearSuspense() {
    this.suspense = {
      suspenseAccountId: 0,
      suspenseDate: "",
      suspenseSourceId: 0,
      suspenseSourceDescription: "",
      suspenseSourceValue: "",
      suspenseSourceRefId: 0,
      suspenseReasonId: 0,
      suspenseReasonDescription: "",
      suspenseReasonValue: "",
      suspenseStatusId: 0,
      suspenseStatusDescription: "",
      suspenseStatusValue: "",
      actionStatusId: 0,
      actionStatusDescription: "",
      actionStatusValue: "",
      suspenseAmt: "",
      orgId: 0,
      fnpfId: "",
      personId: 0,
      memberAccountId: 0,
      postedDate: "",
      errorStatusId: 0,
      errorStatusDescription: "",
      errorStatusValue: "",
      suppressWarningsFlag: "",
      resolvedDate: "",
      firstName: "",
      middleName: "",
      lastName: "",
      tin: "",
      birthDate: "",
      canNotIdentifyFlag: "",
      withdrawalApplicationId: 0,
      creditMemoId: 0,
      creditMemoCreatedDate: "",
      includeInDebtFlag: "",
      memberFullName: "",
      csMonth: "",
      csYear: 0,
      mobileNo: "",
      accountTypeDescription: "",
      accountStatusDescription: "",
      csMonthDescription: "",
      promisMemberFullName: "",
      isRefund: false,
      memberAccountStartDate: "",
      memberAccountEndDate: "",
      protoSuspenseRefundForm: {
        suspenseRefundFormId: 0,
        suspenseId: 0,
        organizationId: 0,
        orgContactId: 0,
        uploadedFileName: "",
        uploadedDate: "",
        contentServerDocId: 0,
        communicationId: 0,
        pdocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
        documentFileId: 0,
      },
      protoPhotoIdentity: {
        suspenseRefundFormId: 0,
        suspenseId: 0,
        organizationId: 0,
        orgContactId: 0,
        uploadedFileName: "",
        uploadedDate: "",
        contentServerDocId: 0,
        communicationId: 0,
        pdocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
        documentFileId: 0,
      },
      wagesMonth: "",
      wagesYear: 0,
      wagesMonthDescription: "",
      updateSeq: 0,
    };
  }
}
