import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class NewWithdrawalsService {
  selectParams = {
    WAEmploymentStatus: [],
    WAPaymentOptions: [],
    WANewBanks: [],
  };

  xData = {
    check_previous_bank: "",
    withdrawalApplicationId: 0,
    applicationTypeId: 0,
    applicationTypeValue: "",
    applicationSubTypeId: 0,
    applicationSubTypeValue: "",
    fnpfNo: "",
    personId: 0,
    orgRefNo: "",
    orgId: 0,
    birthRegNo: "",
    employmentStatusId: 0,
    employmentStatusValue: "",
    categoryId: 0,
    categoryValue: "",
    paymentMethodId: 0,
    paymentMethodValue: "",
    memberConsent: "",
    withdrawalStatusId: 0,
    withdrawalStatusValue: "",
    officerConsent: "",
    applicationTypeDescription: "",
    applicationSubTypeDescription: "",
    employmentStatusDescription: "",
    categoryDescription: "",
    paymentMethodDescription: "",
    withdrawalStatusDescription: "",
    fullname: "",
    dateOfBirth: "",
    createdDate: "",
    phase: "",
    transactionPin: "",
    memberConcentMsg: "",
    officerConcentMsg: "",
    infoMsg: "",
    plstWithdrawalDocuments: [],
    pWithdrawalApplicationSummary: {
      rejectedApplication: "",
      existingApplication: "",
      completedApplication: "",
      categoryOneApplication: "",
    },
    bankAccountNumber: "",
    bankAccountName: "",
    promisWithdrawalApplicationId: 0,
    memberConsentDescription: "",
    bankName: "",
    istrCurrentStatus: "",
    documentContentId: 0,
    plstPreviuoslyUsedBanks: [],
    plstNewBanks: [],
    bankOrgRefNo: "",
    bankOrgId: 0,
    bankAccountId: 0,
    mpaisaMobileNo: "",
    istrExistingMobileNo: "",
    istrNewPayment: "",
    newMobileNo: "",
    idoObjState: "",
    updateSeq: 0
  };

  documents = [
    {
      withdrawalApplicationDocumentId: 0,
      withdrawalApplicationId: 0,
      documentTypeId: 0,
      documentTypeValue: "APFRM",
      documentFileId: "",
      isMandatory: "",
      documentTypeDescription: "COVID Application From",
      idoObjState: "",
      updateSeq: 0,
      pDocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0
      },
    },
    {
      documentTypeDescription: "Birth Registration Certificate",
      withdrawalApplicationDocumentId: 0,
      withdrawalApplicationId: 0,
      documentTypeId: 0,
      documentTypeValue: "BRTCT",
      documentFileId: "",
      isMandatory: "",
      idoObjState: "",
      updateSeq: 0,
      pDocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0
      },
    },
    {
      withdrawalApplicationDocumentId: 0,
      withdrawalApplicationId: 0,
      documentTypeId: 0,
      documentTypeValue: "MSHCD",
      documentFileId: "",
      isMandatory: "",
      documentTypeDescription: "FNPF ID Card",
      idoObjState: "",
      updateSeq: 0,
      pDocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0
      },
    },
    {
      withdrawalApplicationDocumentId: 0,
      withdrawalApplicationId: 0,
      documentTypeId: 0,
      documentTypeValue: "VLDID",
      documentFileId: "",
      isMandatory: "",
      documentTypeDescription: "Valid ID",
      idoObjState: "",
      updateSeq: 0,
      pDocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0,
      },
    },
    {
      withdrawalApplicationDocumentId: 0,
      withdrawalApplicationId: 0,
      documentTypeId: 0,
      documentTypeValue: "BKSTM",
      documentFileId: "",
      isMandatory: "",
      documentTypeDescription: "Bank Statement",
      idoObjState: "",
      updateSeq: 0,
      pDocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0,
      },
    },
    {
      withdrawalApplicationDocumentId: 0,
      withdrawalApplicationId: 0,
      documentTypeId: 0,
      documentTypeValue: "OTHER",
      documentFileId: "",
      isMandatory: "",
      documentTypeDescription: "Other Documents",
      idoObjState: "",
      updateSeq: 0,
      pDocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0
      },
    },
  ];

  newBank = {
    bankAccountNumber: "",
    bankAccountName: "",
    bankName: "",
    bankOrgRefNo: "",
    bankOrgId: 0,
    bankAccountId: 0,
  };

  clearNewbank() {
    this.newBank = {
      bankAccountNumber: "",
      bankAccountName: "",
      bankName: "",
      bankOrgRefNo: "",
      bankOrgId: 0,
      bankAccountId: 0,
    };
  }

  clearWithdrawal() {
    console.log("Clear Called");
    this.newBank = {
      bankAccountNumber: "",
      bankAccountName: "",
      bankName: "",
      bankOrgRefNo: "",
      bankOrgId: 0,
      bankAccountId: 0,
    };

    this.xData = {
      check_previous_bank: "",
      withdrawalApplicationId: 0,
      applicationTypeId: 0,
      applicationTypeValue: "",
      applicationSubTypeId: 0,
      applicationSubTypeValue: "",
      fnpfNo: "",
      personId: 0,
      orgRefNo: "",
      orgId: 0,
      birthRegNo: "",
      employmentStatusId: 0,
      employmentStatusValue: "",
      categoryId: 0,
      categoryValue: "",
      paymentMethodId: 0,
      paymentMethodValue: "",
      memberConsent: "",
      withdrawalStatusId: 0,
      withdrawalStatusValue: "",
      officerConsent: "",
      applicationTypeDescription: "",
      applicationSubTypeDescription: "",
      employmentStatusDescription: "",
      categoryDescription: "",
      paymentMethodDescription: "",
      withdrawalStatusDescription: "",
      fullname: "",
      dateOfBirth: "",
      createdDate: "",
      phase: "",
      transactionPin: "",
      memberConcentMsg: "",
      officerConcentMsg: "",
      infoMsg: "",
      plstWithdrawalDocuments: [],
      pWithdrawalApplicationSummary: {
        rejectedApplication: "",
        existingApplication: "",
        completedApplication: "",
        categoryOneApplication: "",
      },
      bankAccountNumber: "",
      bankAccountName: "",
      promisWithdrawalApplicationId: 0,
      memberConsentDescription: "",
      bankName: "",
      istrCurrentStatus: "",
      documentContentId: 0,
      plstPreviuoslyUsedBanks: [],
      plstNewBanks: [],
      bankOrgRefNo: "",
      bankOrgId: 0,
      bankAccountId: 0,
      mpaisaMobileNo: "",
      istrExistingMobileNo: "",
      istrNewPayment: "",
      newMobileNo: "",
      idoObjState: "",
      updateSeq: 0
    };

    this.documents = [
      {
        withdrawalApplicationDocumentId: 0,
        withdrawalApplicationId: 0,
        documentTypeId: 0,
        documentTypeValue: "APFRM",
        documentFileId: "",
        isMandatory: "",
        documentTypeDescription: "COVID Application From",
        idoObjState: "",
        updateSeq: 0,
        pDocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
      },
      {
        documentTypeDescription: "Birth Registration Certificate",
        withdrawalApplicationDocumentId: 0,
        withdrawalApplicationId: 0,
        documentTypeId: 0,
        documentTypeValue: "BRTCT",
        documentFileId: "",
        isMandatory: "",
        idoObjState: "",
        updateSeq: 0,
        pDocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
      },
      {
        withdrawalApplicationDocumentId: 0,
        withdrawalApplicationId: 0,
        documentTypeId: 0,
        documentTypeValue: "MSHCD",
        documentFileId: "",
        isMandatory: "",
        documentTypeDescription: "FNPF ID Card",
        idoObjState: "",
        updateSeq: 0,
        pDocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
      },
      {
        withdrawalApplicationDocumentId: 0,
        withdrawalApplicationId: 0,
        documentTypeId: 0,
        documentTypeValue: "VLDID",
        documentFileId: "",
        isMandatory: "",
        documentTypeDescription: "Valid ID",
        idoObjState: "",
        updateSeq: 0,
        pDocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
      },
      {
        withdrawalApplicationDocumentId: 0,
        withdrawalApplicationId: 0,
        documentTypeId: 0,
        documentTypeValue: "BKSTM",
        documentFileId: "",
        isMandatory: "",
        documentTypeDescription: "Bank Statement",
        idoObjState: "",
         updateSeq: 0,
        pDocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
      },
      {
        withdrawalApplicationDocumentId: 0,
        withdrawalApplicationId: 0,
        documentTypeId: 0,
        documentTypeValue: "OTHER",
        documentFileId: "",
        isMandatory: "",
        documentTypeDescription: "Other Documents",
        idoObjState: "",
        updateSeq: 0,
        pDocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
      },
    ];
  }

  constructor() {}
}
