import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class HousingAssistanceService {
  DDL = {
    HWLandType: [],
    DDLCountry: [],
    DDLMemberAffect: [],
    DDLLandType: [],
    DDLPreferredCommunication: [],
    DDLApplicationStatus: []
  };
  ProtoHousingAssitanceApplication = {
    housingAssistanceApplicationId: 0,
    orgContactId: 0,
    userSerialId: 0,
    orgId: 0,
    orgBranchId: 0,
    statusId: 0,
    statusValue: '',
    totalRequestedAmount: '',
    commencementDate: '',
    statusDescription: '',
    plstApplicants: [],
    pHousingProperty: {
      housingAssistancePreopertyId: 0,
      housingAssistanceApplicationId: 0,
      landTypeId: 0,
      landTypeValue: '',
      titleNo: '',
      lotNo: '',
      dpSoNlcNo: '',
      housingAssistanceAddressId: 0,
      pAddress: {
        housingAssistanceAddressId: 0,
        boxNo: '',
        postOfficeName: '',
        province: '',
        subDivision: '',
        cityTown: '',
        country: '',
        line1: '',
        line2: '',
        line3: '',
        addressTypeId: 0,
        addressTypeValue: '',
        address: '',
        idoObjState: '',
        updateSeq: 0
      },
      idoObjState: '',
      updateSeq: 0
    },
    pLoadDetail: {
      housingAssistanceLoanDetailId: 0,
      housingAssistanceApplicationId: 0,
      loanAccountName: '',
      loanAccountNumber: '',
      totalLoanAmount: '',
      outstandingLoanBalance: '',
      monthlyRepaymentAmount: '',
      repaymentPeriod: 0,
      remainingPaymentPeriod: 0,
      moratoriumEffectiveDate: '',
      moratoriumTerm: 0,
      originalLoanAmount: '',
      originalLoanEffectiveDate: '',
      existingHousingLoanAmount: '',
      dateOfExistingHousingLoan: '',
      existingHomeLoanArrearAmount: '',
      existingNonHousingLoanAmount: '',
      existingNonHomeLoanArrearAmount: '',
      variableInterstRate: '',
      lastMonthlyInstallmentPaidDate: '',
      idoObjState: '',
      updateSeq: 0
    },
    pApplicant: {
      housingAssistanceApplicantId: 0,
      housingAssistanceApplicationId: 0,
      housingAssistanceEligiblityId: 0,
      promisApplicationId: 0,
      isPrimary: '',
      fnpfNo: '',
      personId: 0,
      tin: '',
      firstName: '',
      middleName: '',
      lastName: '',
      genderId: 0,
      genderValue: '',
      brn: '',
      dob: '',
      currentEmpName: '',
      marriedName: '',
      isLocal: '',
      modeOfCommunicationId: 0,
      modeOfCommunicationValue: '',
      homePhoneNo: '',
      workNo: '',
      mobileNo: '',
      emailId: '',
      memberPhoto: '',
      memberPhotoPath: '',
      sdbFlag: '',
      gaBalance: '',
      paBalance: '',
      pa2Balance: '',
      monthlyRepaymentAmount: '',
      repaymentPeriod: 0,
      memberEligibilityAmount: '',
      actualMemberEligibility: '',
      revisedRepaymentPeriod: 0,
      financialDifficultyId: 0,
      financialDifficultyValue: '',
      postalAddressId: 0,
      residentialAddressId: 0,
      occupation: '',
      requestedAmount: '',
      defaulterFlag: '',
      memberConsent: '',
      pPostalAddress: {
        housingAssistanceAddressId: 0,
        boxNo: '',
        postOfficeName: '',
        province: '',
        subDivision: '',
        cityTown: '',
        country: '',
        line1: '',
        line2: '',
        line3: '',
        addressTypeId: 0,
        addressTypeValue: '',
        address: '',
        idoObjState: '',
        updateSeq: 0
      },
      pResidentialAddress: {
        housingAssistanceAddressId: 0,
        boxNo: '',
        postOfficeName: '',
        province: '',
        subDivision: '',
        cityTown: '',
        country: '',
        line1: '',
        line2: '',
        line3: '',
        addressTypeId: 0,
        addressTypeValue: '',
        address: '',
        idoObjState: '',
        updateSeq: 0
      },
      plstDocument: [],
      applicantApplicationStatusDescription: '',
      genderDescription: '',
      approvedAmount: '',
      idoObjState: '',
      updateSeq: 0
    },
    plstDocument: [],
    plstChecklist: [],
    bankName: '',
    orgContactName: '',
    approvedDate: '',
    branchName: '',
    createdDate: '',
    fnpfNo: '',
    orgRefNo: '',
    applicationConcent: '',
    computedRepaymentAmount: '',
    computedRepaymentPeriod: 0,
    fnpfName: '',
    notes: '',
    idoObjState: '',
    updateSeq: 0,
    pcheckList: {
      housingAssitanceApplicationChecklistId: 0,
      housingAssistanceApplicationId: 0,
      checklistTypeId: 0,
      checklistTypeValue: '',
      isMandatory: '',
      isChecked: '',
      checklistTypeDescription: '',
      checkedDate: '',
      checkedBy: '',
      idoObjState: '',
      updateSeq: 0
    }
  };

  // ProtoHousingAssitanceApplicant = {
  //   housingAssistanceApplicantId: 0,
  //   housingAssistanceApplicationId: 0,
  //   housingAssistanceEligiblityId: 0,
  //   promisApplicationId: 0,
  //   isPrimary: "",
  //   fnpfNo: "",
  //   personId: 0,
  //   tin: "",
  //   firstName: "",
  //   middleName: "",
  //   lastName: "",
  //   genderId: 0,
  //   genderValue: "",
  //   brn: "",
  //   dob: "",
  //   currentEmpName: "",
  //   marriedName: "",
  //   isLocal: "",
  //   modeOfCommunicationId: 0,
  //   modeOfCommunicationValue: "",
  //   homePhoneNo: "",
  //   workNo: "",
  //   mobileNo: "",
  //   emailId: "",
  //   memberPhoto: "",
  //   memberPhotoPath: "",
  //   sdbFlag: "",
  //   gaBalance: "",
  //   paBalance: "",
  //   pa2Balance: "",
  //   monthlyRepaymentAmount: "",
  //   repaymentPeriod: 0,
  //   memberEligibilityAmount: "",
  //   actualMemberEligibility: "",
  //   revisedRepaymentPeriod: 0,
  //   financialDifficultyId: 0,
  //   financialDifficultyValue: "",
  //   postalAddressId: 0,
  //   residentialAddressId: 0,
  //   occupation: "",
  //   requestedAmount: "",
  //   defaulterFlag: "",
  //   memberConsent: "",
  //   pPostalAddress: {
  //     housingAssistanceAddressId: 0,
  //     boxNo: "",
  //     postOfficeName: "",
  //     province: "",
  //     subDivision: "",
  //     cityTown: "",
  //     country: "",
  //     line1: "",
  //     line2: "",
  //     line3: "",
  //     addressTypeId: 0,
  //     addressTypeValue: "",
  //     address:''
  //   },
  //   pResidentialAddress: {
  //     housingAssistanceAddressId: 0,
  //     boxNo: "",
  //     postOfficeName: "",
  //     province: "",
  //     subDivision: "",
  //     cityTown: "",
  //     country: "",
  //     line1: "",
  //     line2: "",
  //     line3: "",
  //     addressTypeId: 0,
  //     addressTypeValue: "",
  //     address:''
  //   },
  //   plstDocument: [],
  // };

  constructor() { }

  clearData() {
    this.ProtoHousingAssitanceApplication = {
      housingAssistanceApplicationId: 0,
      orgContactId: 0,
      userSerialId: 0,
      orgId: 0,
      orgBranchId: 0,
      statusId: 0,
      statusValue: '',
      totalRequestedAmount: '',
      commencementDate: '',
      statusDescription: '',
      plstApplicants: [],
      pHousingProperty: {
        housingAssistancePreopertyId: 0,
        housingAssistanceApplicationId: 0,
        landTypeId: 0,
        landTypeValue: '',
        titleNo: '',
        lotNo: '',
        dpSoNlcNo: '',
        housingAssistanceAddressId: 0,
        pAddress: {
          housingAssistanceAddressId: 0,
          boxNo: '',
          postOfficeName: '',
          province: '',
          subDivision: '',
          cityTown: '',
          country: '',
          line1: '',
          line2: '',
          line3: '',
          addressTypeId: 0,
          addressTypeValue: '',
          address: '',
          idoObjState: '',
          updateSeq: 0
        },
        idoObjState: '',
        updateSeq: 0
      },
      pLoadDetail: {
        housingAssistanceLoanDetailId: 0,
        housingAssistanceApplicationId: 0,
        loanAccountName: '',
        loanAccountNumber: '',
        totalLoanAmount: '',
        outstandingLoanBalance: '',
        monthlyRepaymentAmount: '',
        repaymentPeriod: 0,
        remainingPaymentPeriod: 0,
        moratoriumEffectiveDate: '',
        moratoriumTerm: 0,
        originalLoanAmount: '',
        originalLoanEffectiveDate: '',
        existingHousingLoanAmount: '',
        dateOfExistingHousingLoan: '',
        existingHomeLoanArrearAmount: '',
        existingNonHousingLoanAmount: '',
        existingNonHomeLoanArrearAmount: '',
        variableInterstRate: '',
        lastMonthlyInstallmentPaidDate: '',
        idoObjState: '',
        updateSeq: 0
      },
      pApplicant: {
        housingAssistanceApplicantId: 0,
        housingAssistanceApplicationId: 0,
        housingAssistanceEligiblityId: 0,
        promisApplicationId: 0,
        isPrimary: '',
        fnpfNo: '',
        personId: 0,
        tin: '',
        firstName: '',
        middleName: '',
        lastName: '',
        genderId: 0,
        genderValue: '',
        brn: '',
        dob: '',
        currentEmpName: '',
        marriedName: '',
        isLocal: '',
        modeOfCommunicationId: 0,
        modeOfCommunicationValue: '',
        homePhoneNo: '',
        workNo: '',
        mobileNo: '',
        emailId: '',
        memberPhoto: '',
        memberPhotoPath: '',
        sdbFlag: '',
        gaBalance: '',
        paBalance: '',
        pa2Balance: '',
        monthlyRepaymentAmount: '',
        repaymentPeriod: 0,
        memberEligibilityAmount: '',
        actualMemberEligibility: '',
        revisedRepaymentPeriod: 0,
        financialDifficultyId: 0,
        financialDifficultyValue: '',
        postalAddressId: 0,
        residentialAddressId: 0,
        occupation: '',
        requestedAmount: '',
        defaulterFlag: '',
        memberConsent: '',
        pPostalAddress: {
          housingAssistanceAddressId: 0,
          boxNo: '',
          postOfficeName: '',
          province: '',
          subDivision: '',
          cityTown: '',
          country: '',
          line1: '',
          line2: '',
          line3: '',
          addressTypeId: 0,
          addressTypeValue: '',
          address: '',
          idoObjState: '',
          updateSeq: 0
        },
        pResidentialAddress: {
          housingAssistanceAddressId: 0,
          boxNo: '',
          postOfficeName: '',
          province: '',
          subDivision: '',
          cityTown: '',
          country: '',
          line1: '',
          line2: '',
          line3: '',
          addressTypeId: 0,
          addressTypeValue: '',
          address: '',
          idoObjState: '',
          updateSeq: 0
        },
        plstDocument: [],
        applicantApplicationStatusDescription: '',
        genderDescription: '',
        approvedAmount: '',
        idoObjState: '',
        updateSeq: 0
      },
      plstDocument: [],
      plstChecklist: [],
      bankName: '',
      orgContactName: '',
      approvedDate: '',
      branchName: '',
      createdDate: '',
      fnpfNo: '',
      orgRefNo: '',
      applicationConcent: '',
      computedRepaymentAmount: '',
      computedRepaymentPeriod: 0,
      fnpfName: '',
      notes: '',
      idoObjState: '',
      updateSeq: 0,
      pcheckList: {
        housingAssitanceApplicationChecklistId: 0,
        housingAssistanceApplicationId: 0,
        checklistTypeId: 0,
        checklistTypeValue: '',
        isMandatory: '',
        isChecked: '',
        checklistTypeDescription: '',
        checkedDate: '',
        checkedBy: '',
        idoObjState: '',
        updateSeq: 0
      }
    };
  }
}
