import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class viewcontactservice {
  contact = {
    person: {
      firstName: "",
      middleName: "",
      lastName: "",
      dateOfBirth: "",
      gender_id: "",
      genderValue: "",
      genderDescription: "",
      father_name: "",
      mother_name: "",
      fnpf_no: "",
      tin: "",
      passportNo: "",
      birthRegNo: "",
      personId: 0,
      mobile_no: "",
      email_id: "",
      citizenship_id: "",
      citizenship_value: "",
      citizenship_description: "",
      ethnicity_id: "",
      ethnicity_value: "",
      ethnicity_description: "",
      national_id: "",
      national_value: "",
      national_description: "",
    },
    primaryContactDeactivated: "",
    orgRefNo: "",
    orgId: 0,
    contactTypeId: 0,
    contactTypeValue: "",
    contactTypeDescription: "",
    contactStatusId: 0,
    contactStatusValue: "",
    contactStatusDescription: "",
    holdingPercentage: 0,
    startDate: "",
    endDate: "",
    emailId: "",
    contactNo: "",
    employerContactId: 0,
    orgAddressId: 0,
    lstEntAdderss: [],
    lstprotoentCSCode: [],
    lstprotoListOfContactType: [],
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [],
      hasError: true,
    },
    employerContactAddress: {
      employerContactAddressId: 0,
      employerContactId: 0,
      line1: "",
      line2: "",
      city: "",
      province: "",
      island: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [],
        hasError: true,
      },
    },
    protoListOfContactType: {
      contactType: "",
      contactTypeDescription: "",
      isActive: "",
    },
    protoentCSCode: {
      csCodeId: 0,
      orgId: 0,
      csCode: "",
      isActive: "",
    },
    updateSeq: 0,
  };
  getcontactsearch = {
    firstname: "",
    middlename: "",
    begindatefrom: "",
    begindateto: "",
  };
  DDL: any = {
    DDLStatusValue: [],
  };
  constructor() {}
  clearContact() {
    this.contact = {
      person: {
        firstName: "",
        middleName: "",
        lastName: "",
        dateOfBirth: "",
        gender_id: "",
        genderValue: "",
        genderDescription: "",
        father_name: "",
        mother_name: "",
        fnpf_no: "",
        tin: "",
        passportNo: "",
        birthRegNo: "",
        personId: 0,
        mobile_no: "",
        email_id: "",
        citizenship_id: "",
        citizenship_value: "",
        citizenship_description: "",
        ethnicity_id: "",
        ethnicity_value: "",
        ethnicity_description: "",
        national_id: "",
        national_value: "",
        national_description: "",
      },
      orgAddressId: 0,
      lstEntAdderss: [],
      primaryContactDeactivated: "",
      orgRefNo: "",
      orgId: 0,
      contactTypeId: 0,
      contactTypeValue: "",
      contactTypeDescription: "",
      contactStatusId: 0,
      contactStatusValue: "",
      contactStatusDescription: "",
      holdingPercentage: 0,
      startDate: "",
      endDate: "",
      emailId: "",
      contactNo: "",
      employerContactId: 0,
      lstprotoentCSCode: [],
      lstprotoListOfContactType: [],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [],
        hasError: true,
      },
      employerContactAddress: {
        employerContactAddressId: 0,
        employerContactId: 0,
        line1: "",
        line2: "",
        city: "",
        province: "",
        island: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [],
          hasError: true,
        },
      },
      protoListOfContactType: {
        contactType: "",
        contactTypeDescription: "",
        isActive: "",
      },
      protoentCSCode: {
        csCodeId: 0,
        orgId: 0,
        csCode: "",
        isActive: "",
      },
      updateSeq: 0,
    };
  }
}
