import { Injectable } from "@angular/core";
import { FullSpinnerService } from "src/app/common/full-spinner/full-spinner.service";

@Injectable({
  providedIn: "root",
})
export class DpoService {
  dpoId = 0;
  dpoHeaderId = 0;
  dpoRequestId = 0;
  loadingTrue = false;
  btnClicked = false;
  errorTrue = false;
  constructor(public fullspinner: FullSpinnerService) {}
  viewDpo = {
    ientPerson: {
      firstName: "",
      middleName: "",
      lastName: "",
      dateOfBirth: "",
      genderId: 0,
      genderValue: "",
      genderDescription: "",
      fatherName: "",
      motherName: "",
      fnpfNo: "",
      tin: "",
      passportNo: "",
      personId: 0,
      mobileNo: "",
      emailId: "",
      citizenshipId: 0,
      citizenshipValue: "",
      citizenshipDescription: "",
      ethnicityId: 0,
      ethnicityValue: "",
      ethnicityDescription: "",
      nationalId: 0,
      nationalValue: "",
      nationalDescription: "",
      maritalStatusId: 0,
      maritalStatusValue: "",
      maritalStatusDescription: "",
      personStatusId: 0,
      personStatusValue: "",
      personStatusDescription: "",
      peopleHubId: 0,
      errorStatusId: 0,
      errorStatusValue: "",
      actionStatusId: 0,
      actionStatusValue: "",
      interfaceStatusId: 0,
      interfaceStatusValue: "",
      hotlistFlag: "",
      suppressWarningsFlag: "",
      duplicateFlag: "",
      cAndFNotificationFlag: "",
      birthRegNo: "",
      employmentStartDate: "",
      employmentEndDate: "",
      lastContributionMonthYear: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
    },
    ilstentDPOHeader: [
      {
        dpoHeaderId: 0,
        dpoEffectiveDate: "",
        dpoEndDate: "",
        orgId: 0,
        invoiceAmount: "",
        ilstprotoentDPODetail: [
          {
            dpoDetailId: 0,
            dpoHeaderId: 0,
            orgContactId: 0,
            upliftStatusId: 0,
            upliftStatusDescription: "",
            upliftStatusValue: "",
            upliftActionStatusId: 0,
            upliftActionStatusDescription: "",
            upliftActionStatusValue: "",
            ilstprotoentDpoDetailStatusHistory: [
              {
                dpoDetailId: 0,
                statusTypeId: 0,
                statusTypeDescription: "",
                statusTypeValue: "",
                upliftStatusId: 0,
                upliftStatusDescription: "",
                upliftStatusValue: "",
                statusEffectiveDate: "",
              },
            ],
            ilstprotoentDpoChecklist: [
              {
                dpoDetailId: 0,
                checklistDocumentId: 0,
                checklistDocumentDescription: "",
                checklistDocumentValue: "",
                documentReceivedDate: "",
                mandatoryFlag: "",
                mandatoryFlagDisplay: "",
              },
            ],
          },
        ],
        ientOrganization: {
          orgId: 0,
          businessName: "",
          tradeName: "",
          orgRefNo: "",
          tin: "",
          businessRegNo: "",
          businessRegDate: "",
          businessLicenseNo: "",
          fircNo: "",
          natureOfBusiness: "",
          orgStatusId: 0,
          orgStatusValue: "",
          orgStatusDescription: "",
          overseasOrg: true,
          lstOrgContact: [
            {
              person: {
                firstName: "",
                middleName: "",
                lastName: "",
                dateOfBirth: "",
                genderId: 0,
                genderValue: "",
                genderDescription: "",
                fatherName: "",
                motherName: "",
                fnpfNo: "",
                tin: "",
                passportNo: "",
                personId: 0,
                mobileNo: "",
                emailId: "",
                citizenshipId: 0,
                citizenshipValue: "",
                citizenshipDescription: "",
                ethnicityId: 0,
                ethnicityValue: "",
                ethnicityDescription: "",
                nationalId: 0,
                nationalValue: "",
                nationalDescription: "",
                maritalStatusId: 0,
                maritalStatusValue: "",
                maritalStatusDescription: "",
                personStatusId: 0,
                personStatusValue: "",
                personStatusDescription: "",
                peopleHubId: 0,
                errorStatusId: 0,
                errorStatusValue: "",
                actionStatusId: 0,
                actionStatusValue: "",
                interfaceStatusId: 0,
                interfaceStatusValue: "",
                hotlistFlag: "",
                suppressWarningsFlag: "",
                duplicateFlag: "",
                cAndFNotificationFlag: "",
                birthRegNo: "",
                employmentStartDate: "",
                employmentEndDate: "",
                lastContributionMonthYear: "",
                msg: {
                  infoMessage: {
                    msgID: 0,
                    msgType: 0,
                    msgDescription: "",
                  },
                  errorMessage: [
                    {
                      msgID: 0,
                      msgType: 0,
                      msgDescription: "",
                    },
                  ],
                  hasError: true,
                },
              },
              orgRefNo: "",
              orgId: 0,
              contactTypeId: 0,
              contactTypeValue: "",
              contactTypeDescription: "",
              contactStatusId: 0,
              contactStatusValue: "",
              contactStatusDescription: "",
              holdingPercentage: "",
              startDate: "",
              endDate: "",
              emailId: "",
              contactNo: "",
              employerContactId: 0,
              lstprotoentOrganization: [null],
              msg: {
                infoMessage: {
                  msgID: 0,
                  msgType: 0,
                  msgDescription: "",
                },
                errorMessage: [
                  {
                    msgID: 0,
                    msgType: 0,
                    msgDescription: "",
                  },
                ],
                hasError: true,
              },
              protoentAddress: {
                personId: 0,
                orgId: 0,
                addressId: 0,
                line1: "",
                line2: "",
                city: "",
                province: "",
                source: "",
                addressType: "",
                status: "",
                countryValue: "",
                countryDescription: "",
                island: "",
                createdDate: "",
                addressTypeDescription: "",
              },
              lstprotoListOfContactType: [
                {
                  contactType: "",
                  contactTypeDescription: "",
                  isActive: "",
                },
              ],
              lstprotoentCSCode: [
                {
                  csCodeId: 0,
                  orgId: 0,
                  csCode: "",
                  isActive: "",
                  description: "",
                  effectiveDate: "",
                  endDate: "",
                },
              ],
              primaryContactDeactivated: "",
              commaSeparatedContactType: "",
              registeredStatus: "",
              orgAddressId: 0,
              lstEntAdderss: [
                {
                  personId: 0,
                  orgId: 0,
                  addressId: 0,
                  line1: "",
                  line2: "",
                  city: "",
                  province: "",
                  source: "",
                  addressType: "",
                  status: "",
                  countryValue: "",
                  countryDescription: "",
                  island: "",
                  createdDate: "",
                  addressTypeDescription: "",
                },
              ],
              personId: 0,
              protoListOfContactType: {
                contactType: "",
                contactTypeDescription: "",
                isActive: "",
              },
              protoentCSCode: {
                csCodeId: 0,
                orgId: 0,
                csCode: "",
                isActive: "",
                description: "",
                effectiveDate: "",
                endDate: "",
              },
              commaSeparatedCsCode: "",
            },
          ],
          msg: {
            infoMessage: {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
            errorMessage: [
              {
                msgID: 0,
                msgType: 0,
                msgDescription: "",
              },
            ],
            hasError: true,
          },
          lstEntAdderss: [
            {
              personId: 0,
              orgId: 0,
              addressId: 0,
              line1: "",
              line2: "",
              city: "",
              province: "",
              source: "",
              addressType: "",
              status: "",
              countryValue: "",
              countryDescription: "",
              island: "",
              createdDate: "",
              addressTypeDescription: "",
            },
          ],
          lstEntCommunication: [
            {
              orgCommunicationId: 0,
              orgId: 0,
              orgReFNo: "",
              orgCommunicationTypeId: 0,
              orgCommunicationTypeValue: "",
              orgCommunicationTypeDescription: "",
              orgCommunicationStatusId: 0,
              orgCommunicationStatusValue: "",
              orgCommunicationStatusDescription: "",
              communicationDetail: "",
            },
          ],
          protoentAddress: {
            personId: 0,
            orgId: 0,
            addressId: 0,
            line1: "",
            line2: "",
            city: "",
            province: "",
            source: "",
            addressType: "",
            status: "",
            countryValue: "",
            countryDescription: "",
            island: "",
            createdDate: "",
            addressTypeDescription: "",
          },
          protoentOrgCommunication: {
            orgCommunicationId: 0,
            orgId: 0,
            orgReFNo: "",
            orgCommunicationTypeId: 0,
            orgCommunicationTypeValue: "",
            orgCommunicationTypeDescription: "",
            orgCommunicationStatusId: 0,
            orgCommunicationStatusValue: "",
            orgCommunicationStatusDescription: "",
            communicationDetail: "",
          },
        },
        ientOrgContact: {
          person: {
            firstName: "",
            middleName: "",
            lastName: "",
            dateOfBirth: "",
            genderId: 0,
            genderValue: "",
            genderDescription: "",
            fatherName: "",
            motherName: "",
            fnpfNo: "",
            tin: "",
            passportNo: "",
            personId: 0,
            mobileNo: "",
            emailId: "",
            citizenshipId: 0,
            citizenshipValue: "",
            citizenshipDescription: "",
            ethnicityId: 0,
            ethnicityValue: "",
            ethnicityDescription: "",
            nationalId: 0,
            nationalValue: "",
            nationalDescription: "",
            maritalStatusId: 0,
            maritalStatusValue: "",
            maritalStatusDescription: "",
            personStatusId: 0,
            personStatusValue: "",
            personStatusDescription: "",
            peopleHubId: 0,
            errorStatusId: 0,
            errorStatusValue: "",
            actionStatusId: 0,
            actionStatusValue: "",
            interfaceStatusId: 0,
            interfaceStatusValue: "",
            hotlistFlag: "",
            suppressWarningsFlag: "",
            duplicateFlag: "",
            cAndFNotificationFlag: "",
            birthRegNo: "",
            employmentStartDate: "",
            employmentEndDate: "",
            lastContributionMonthYear: "",
            msg: {
              infoMessage: {
                msgID: 0,
                msgType: 0,
                msgDescription: "",
              },
              errorMessage: [
                {
                  msgID: 0,
                  msgType: 0,
                  msgDescription: "",
                },
              ],
              hasError: true,
            },
          },
          orgRefNo: "",
          orgId: 0,
          contactTypeId: 0,
          contactTypeValue: "",
          contactTypeDescription: "",
          contactStatusId: 0,
          contactStatusValue: "",
          contactStatusDescription: "",
          holdingPercentage: "",
          startDate: "",
          endDate: "",
          emailId: "",
          contactNo: "",
          employerContactId: 0,
          lstprotoentOrganization: [null],
          msg: {
            infoMessage: {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
            errorMessage: [
              {
                msgID: 0,
                msgType: 0,
                msgDescription: "",
              },
            ],
            hasError: true,
          },
          protoentAddress: {
            personId: 0,
            orgId: 0,
            addressId: 0,
            line1: "",
            line2: "",
            city: "",
            province: "",
            source: "",
            addressType: "",
            status: "",
            countryValue: "",
            countryDescription: "",
            island: "",
            createdDate: "",
            addressTypeDescription: "",
          },
          lstprotoListOfContactType: [
            {
              contactType: "",
              contactTypeDescription: "",
              isActive: "",
            },
          ],
          lstprotoentCSCode: [
            {
              csCodeId: 0,
              orgId: 0,
              csCode: "",
              isActive: "",
              description: "",
              effectiveDate: "",
              endDate: "",
            },
          ],
          primaryContactDeactivated: "",
          commaSeparatedContactType: "",
          registeredStatus: "",
          orgAddressId: 0,
          lstEntAdderss: [
            {
              personId: 0,
              orgId: 0,
              addressId: 0,
              line1: "",
              line2: "",
              city: "",
              province: "",
              source: "",
              addressType: "",
              status: "",
              countryValue: "",
              countryDescription: "",
              island: "",
              createdDate: "",
              addressTypeDescription: "",
            },
          ],
          personId: 0,
          protoListOfContactType: {
            contactType: "",
            contactTypeDescription: "",
            isActive: "",
          },
          protoentCSCode: {
            csCodeId: 0,
            orgId: 0,
            csCode: "",
            isActive: "",
            description: "",
            effectiveDate: "",
            endDate: "",
          },
          commaSeparatedCsCode: "",
        },
        iblnShowRevokeBtn: true,
        iblnShowConditionalTravelReqBtn: true,
        lentDPODetail: {
          dpoDetailId: 0,
          dpoHeaderId: 0,
          orgContactId: 0,
          upliftStatusId: 0,
          upliftStatusDescription: "",
          upliftStatusValue: "",
          upliftActionStatusId: 0,
          upliftActionStatusDescription: "",
          upliftActionStatusValue: "",
          ilstprotoentDpoDetailStatusHistory: [
            {
              dpoDetailId: 0,
              statusTypeId: 0,
              statusTypeDescription: "",
              statusTypeValue: "",
              upliftStatusId: 0,
              upliftStatusDescription: "",
              upliftStatusValue: "",
              statusEffectiveDate: "",
            },
          ],
          ilstprotoentDpoChecklist: [
            {
              dpoDetailId: 0,
              checklistDocumentId: 0,
              checklistDocumentDescription: "",
              checklistDocumentValue: "",
              documentReceivedDate: "",
              mandatoryFlag: "",
              mandatoryFlagDisplay: "",
            },
          ],
        },
        selectedDPO: "",
      },
    ],
    iblnShowRevokeBtn: true,
    iblnShowConditionalTravelReqBtn: true,
  };

  dpoRevokeRequest = {
    appDpoRequestId: 0,
    employerPortalUserId: 0,
    loggedInOrgId: 0,
    dpoId: 0,
    dpoOrgId: 0,
    dpoOrgRefNo: "",
    dpoOrgName: "",
    dpoContactTypeId: 0,
    requestTypeId: 0,
    requestTypeValue: "",
    destinationCountryId: 0,
    destinationCountryValue: "",
    departureDate: "",
    destinationArrivalDate: "",
    returnDate: "",
    reasonForTravelId: 0,
    reasonForTravelValue: "",
    comment: "",
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    idoObjState: "",
    updateSeq: 0,
    submittedBy: "",
    submittedDate: "",
    dpoDeptAmt: "",
    dpoPaidAmt: "",
    dpoDate: "",
    plstDpoRequestDocument: [
      {
        appDpoRequestDocumentId: 0,
        appDpoRequestId: 0,
        documentTypeId: 0,
        documentTypeValue: "",
        documentFileId: 0,
        isMandatory: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        idoObjState: "",
        updateSeq: 0,
        documentTypeDescription: "",
        pdocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
        imageData: {
          data: [0],
          msg: {
            infoMessage: {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
            errorMessage: [
              {
                msgID: 0,
                msgType: 0,
                msgDescription: "",
              },
            ],
            hasError: true,
          },
        },
        eitherValue: "",
        orderById: 0,
      },
    ],
    plstDpoRequestEmailHistory: [
      {
        appDpoRequestEmailHistoryId: 0,
        appDpoRequestId: 0,
        communicationTrackingId: 0,
        statusId: 0,
        statusValue: "",
        sentBy: "",
        sentDate: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        idoObjState: "",
        updateSeq: 0,
        statusDescription: "",
      },
    ],
    statusId: 0,
    statusValue: "",
    personId: 0,
    ientDpoRequestDocument :{
      appDpoRequestDocumentId: 0,
      appDpoRequestId: 0,
      documentTypeId: 0,
      documentTypeValue: "",
      documentFileId: 0,
      isMandatory: "",
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
      idoObjState: "",
      updateSeq: 0,
      documentTypeDescription: "",
      pdocumentFile: {
        documentFileId: 0,
        fileType: "",
        fileSize: 0,
        relativePath: "",
        fileName: "",
        uploadbyFullName: "",
        istrFileContent: "",
        idoObjState: "",
        updateSeq: 0,
      },
      imageData: {
        data: [0],
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
      },
      eitherValue: "",
      orderById: 0,
    }
  };
  dpoRevokeRequestDocument = {
    appDpoRequestDocumentId: 0,
    appDpoRequestId: 0,
    documentTypeId: 0,
    documentTypeValue: "",
    documentFileId: 0,
    isMandatory: "",
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    idoObjState: "",
    updateSeq: 0,
    documentTypeDescription: "",
    pdocumentFile: {
      documentFileId: 0,
      fileType: "",
      fileSize: 0,
      relativePath: "",
      fileName: "",
      uploadbyFullName: "",
      istrFileContent: "",
      idoObjState: "",
      updateSeq: 0,
    },
    imageData: {
      data: [0],
      msg: {
        infoMessage: {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
        errorMessage: [
          {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
        ],
        hasError: true,
      },
    },
    eitherValue: "",
    orderById: 0,
  };
  dpoConditionalTravelRequest = {
    appDpoRequestId: 0,
    employerPortalUserId: 0,
    loggedInOrgId: 0,
    dpoId: 0,
    dpoOrgId: 0,
    dpoOrgRefNo: "",
    dpoOrgName: "",
    dpoContactTypeId: 0,
    dpoContactTypeValue: "",
    requestTypeId: 0,
    requestTypeValue: "",
    destinationCountryId: 0,
    destinationCountryValue: "",
    departureDate: "",
    destinationArrivalDate: "",
    returnDate: "",
    reasonForTravelId: 0,
    reasonForTravelValue: "",
    comment: "",
    msg: {
      infoMessage: {
        msgID: 0,
        msgType: 0,
        msgDescription: "",
      },
      errorMessage: [
        {
          msgID: 0,
          msgType: 0,
          msgDescription: "",
        },
      ],
      hasError: true,
    },
    idoObjState: "",
    updateSeq: 0,
    submittedBy: "",
    submittedDate: "",
    dpoDeptAmt: "",
    dpoPaidAmt: "",
    dpoDate: "",
    plstDpoRequestDocument: [
      {
        appDpoRequestDocumentId: 0,
        appDpoRequestId: 0,
        documentTypeId: 0,
        documentTypeValue: "",
        documentFileId: 0,
        isMandatory: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        idoObjState: "",
        updateSeq: 0,
        documentTypeDescription: "",
        pdocumentFile: {
          documentFileId: 0,
          fileType: "",
          fileSize: 0,
          relativePath: "",
          fileName: "",
          uploadbyFullName: "",
          istrFileContent: "",
          idoObjState: "",
          updateSeq: 0,
        },
        imageData: {
          data: [0],
          msg: {
            infoMessage: {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
            errorMessage: [
              {
                msgID: 0,
                msgType: 0,
                msgDescription: "",
              },
            ],
            hasError: true,
          },
        },
        eitherValue: "",
        orderById: 0,
      },
    ],
    plstDpoRequestEmailHistory: [
      {
        appDpoRequestEmailHistoryId: 0,
        appDpoRequestId: 0,
        communicationTrackingId: 0,
        statusId: 0,
        statusValue: "",
        sentBy: "",
        sentDate: "",
        msg: {
          infoMessage: {
            msgID: 0,
            msgType: 0,
            msgDescription: "",
          },
          errorMessage: [
            {
              msgID: 0,
              msgType: 0,
              msgDescription: "",
            },
          ],
          hasError: true,
        },
        idoObjState: "",
        updateSeq: 0,
        statusDescription: "",
      },
    ],
    statusId: 0,
    statusValue: "",
    personId: 0,
    requestTypeDescription: "",
    destinationCountryDescription: "",
    reasonForTravelDescription: "",
    statusDescription: "",
    dpoOrgContactId: 0,
  };
  initialData = {
    DPOStatus: [],
    DPOContactType: [],
    DPODestinationCountry: [],
    DPOReasonForTravel: [],
  };
  setAll(val) {
    this.btnClicked = val;
    this.loadingTrue = val;
    this.fullspinner.empty.next(val);
  }
}
